/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain;


import de.quinscape.automatontest.domain.tables.AppAttachment;
import de.quinscape.automatontest.domain.tables.AppAttachmentData;
import de.quinscape.automatontest.domain.tables.AppConfig;
import de.quinscape.automatontest.domain.tables.AppLogin;
import de.quinscape.automatontest.domain.tables.AppTranslation;
import de.quinscape.automatontest.domain.tables.AppUser;
import de.quinscape.automatontest.domain.tables.AppUserConfig;
import de.quinscape.automatontest.domain.tables.AppVersion;
import de.quinscape.automatontest.domain.tables.Baz;
import de.quinscape.automatontest.domain.tables.BazLink;
import de.quinscape.automatontest.domain.tables.BazValue;
import de.quinscape.automatontest.domain.tables.Corge;
import de.quinscape.automatontest.domain.tables.CorgeAssoc;
import de.quinscape.automatontest.domain.tables.CorgeLink;
import de.quinscape.automatontest.domain.tables.CorgeType;
import de.quinscape.automatontest.domain.tables.Foo;
import de.quinscape.automatontest.domain.tables.FooType;
import de.quinscape.automatontest.domain.tables.Garply;
import de.quinscape.automatontest.domain.tables.Grault;
import de.quinscape.automatontest.domain.tables.GridColumns;
import de.quinscape.automatontest.domain.tables.MetaConfig;
import de.quinscape.automatontest.domain.tables.Node;
import de.quinscape.automatontest.domain.tables.Plugh;
import de.quinscape.automatontest.domain.tables.QuxA;
import de.quinscape.automatontest.domain.tables.QuxB;
import de.quinscape.automatontest.domain.tables.QuxC;
import de.quinscape.automatontest.domain.tables.QuxD;
import de.quinscape.automatontest.domain.tables.QuxMain;
import de.quinscape.automatontest.domain.tables.Waldo;
import de.quinscape.automatontest.domain.tables.records.AppAttachmentDataRecord;
import de.quinscape.automatontest.domain.tables.records.AppAttachmentRecord;
import de.quinscape.automatontest.domain.tables.records.AppConfigRecord;
import de.quinscape.automatontest.domain.tables.records.AppLoginRecord;
import de.quinscape.automatontest.domain.tables.records.AppTranslationRecord;
import de.quinscape.automatontest.domain.tables.records.AppUserConfigRecord;
import de.quinscape.automatontest.domain.tables.records.AppUserRecord;
import de.quinscape.automatontest.domain.tables.records.AppVersionRecord;
import de.quinscape.automatontest.domain.tables.records.BazLinkRecord;
import de.quinscape.automatontest.domain.tables.records.BazRecord;
import de.quinscape.automatontest.domain.tables.records.BazValueRecord;
import de.quinscape.automatontest.domain.tables.records.CorgeAssocRecord;
import de.quinscape.automatontest.domain.tables.records.CorgeLinkRecord;
import de.quinscape.automatontest.domain.tables.records.CorgeRecord;
import de.quinscape.automatontest.domain.tables.records.CorgeTypeRecord;
import de.quinscape.automatontest.domain.tables.records.FooRecord;
import de.quinscape.automatontest.domain.tables.records.FooTypeRecord;
import de.quinscape.automatontest.domain.tables.records.GarplyRecord;
import de.quinscape.automatontest.domain.tables.records.GraultRecord;
import de.quinscape.automatontest.domain.tables.records.GridColumnsRecord;
import de.quinscape.automatontest.domain.tables.records.MetaConfigRecord;
import de.quinscape.automatontest.domain.tables.records.NodeRecord;
import de.quinscape.automatontest.domain.tables.records.PlughRecord;
import de.quinscape.automatontest.domain.tables.records.QuxARecord;
import de.quinscape.automatontest.domain.tables.records.QuxBRecord;
import de.quinscape.automatontest.domain.tables.records.QuxCRecord;
import de.quinscape.automatontest.domain.tables.records.QuxDRecord;
import de.quinscape.automatontest.domain.tables.records.QuxMainRecord;
import de.quinscape.automatontest.domain.tables.records.WaldoRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppAttachmentRecord> PK_APP_ATTACHMENT = UniqueKeys0.PK_APP_ATTACHMENT;
    public static final UniqueKey<AppAttachmentDataRecord> PK_APP_ATTACHMENT_DATA = UniqueKeys0.PK_APP_ATTACHMENT_DATA;
    public static final UniqueKey<AppAttachmentDataRecord> UC_APP_ATTACHMENT_DATA_ATTACHMENT_ID = UniqueKeys0.UC_APP_ATTACHMENT_DATA_ATTACHMENT_ID;
    public static final UniqueKey<AppConfigRecord> PK_APP_CONFIG = UniqueKeys0.PK_APP_CONFIG;
    public static final UniqueKey<AppLoginRecord> PK_APP_LOGIN = UniqueKeys0.PK_APP_LOGIN;
    public static final UniqueKey<AppTranslationRecord> PK_APP_TRANSLATION = UniqueKeys0.PK_APP_TRANSLATION;
    public static final UniqueKey<AppTranslationRecord> UC_APP_TRANSLATION = UniqueKeys0.UC_APP_TRANSLATION;
    public static final UniqueKey<AppUserRecord> PK_APP_USER = UniqueKeys0.PK_APP_USER;
    public static final UniqueKey<AppUserRecord> UC_APP_USER_LOGIN = UniqueKeys0.UC_APP_USER_LOGIN;
    public static final UniqueKey<AppUserConfigRecord> PK_APP_USER_CONFIG = UniqueKeys0.PK_APP_USER_CONFIG;
    public static final UniqueKey<AppVersionRecord> PK_APP_VERSION = UniqueKeys0.PK_APP_VERSION;
    public static final UniqueKey<BazRecord> PK_BAZ = UniqueKeys0.PK_BAZ;
    public static final UniqueKey<BazLinkRecord> PK_BAZ_LINK = UniqueKeys0.PK_BAZ_LINK;
    public static final UniqueKey<BazLinkRecord> BAZ_LINK_BAZ_ID_VALUE_ID_KEY = UniqueKeys0.BAZ_LINK_BAZ_ID_VALUE_ID_KEY;
    public static final UniqueKey<BazValueRecord> PK_BAZ_VALUE = UniqueKeys0.PK_BAZ_VALUE;
    public static final UniqueKey<CorgeRecord> PK_CORGE = UniqueKeys0.PK_CORGE;
    public static final UniqueKey<CorgeAssocRecord> PK_CORGE_ASSOC = UniqueKeys0.PK_CORGE_ASSOC;
    public static final UniqueKey<CorgeLinkRecord> PK_CORGE_LINK = UniqueKeys0.PK_CORGE_LINK;
    public static final UniqueKey<CorgeTypeRecord> PK_CORGE_TYPE = UniqueKeys0.PK_CORGE_TYPE;
    public static final UniqueKey<FooRecord> PK_FOO = UniqueKeys0.PK_FOO;
    public static final UniqueKey<FooTypeRecord> PK_FOO_TYPE = UniqueKeys0.PK_FOO_TYPE;
    public static final UniqueKey<FooTypeRecord> FOO_TYPE_NAME_KEY = UniqueKeys0.FOO_TYPE_NAME_KEY;
    public static final UniqueKey<GarplyRecord> PK_GARPLY = UniqueKeys0.PK_GARPLY;
    public static final UniqueKey<GraultRecord> PK_GRAULT = UniqueKeys0.PK_GRAULT;
    public static final UniqueKey<GridColumnsRecord> PK_GRID_COLUMNS = UniqueKeys0.PK_GRID_COLUMNS;
    public static final UniqueKey<GridColumnsRecord> GRID_COLUMNS_NAME_OWNER_ID_KEY = UniqueKeys0.GRID_COLUMNS_NAME_OWNER_ID_KEY;
    public static final UniqueKey<MetaConfigRecord> PK_META_CONFIG = UniqueKeys0.PK_META_CONFIG;
    public static final UniqueKey<NodeRecord> PK_NODE = UniqueKeys0.PK_NODE;
    public static final UniqueKey<NodeRecord> UC_NODE_NAME = UniqueKeys0.UC_NODE_NAME;
    public static final UniqueKey<PlughRecord> PK_PLUGH = UniqueKeys0.PK_PLUGH;
    public static final UniqueKey<QuxARecord> PK_QUX_A = UniqueKeys0.PK_QUX_A;
    public static final UniqueKey<QuxARecord> QUX_A_NAME_KEY = UniqueKeys0.QUX_A_NAME_KEY;
    public static final UniqueKey<QuxBRecord> PK_QUX_B = UniqueKeys0.PK_QUX_B;
    public static final UniqueKey<QuxBRecord> QUX_B_NAME_KEY = UniqueKeys0.QUX_B_NAME_KEY;
    public static final UniqueKey<QuxCRecord> PK_QUX_C = UniqueKeys0.PK_QUX_C;
    public static final UniqueKey<QuxCRecord> QUX_C_NAME_KEY = UniqueKeys0.QUX_C_NAME_KEY;
    public static final UniqueKey<QuxDRecord> PK_QUX_D = UniqueKeys0.PK_QUX_D;
    public static final UniqueKey<QuxDRecord> QUX_D_NAME_KEY = UniqueKeys0.QUX_D_NAME_KEY;
    public static final UniqueKey<QuxMainRecord> PK_QUX_MAIN = UniqueKeys0.PK_QUX_MAIN;
    public static final UniqueKey<WaldoRecord> PK_WALDO = UniqueKeys0.PK_WALDO;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AppAttachmentDataRecord, AppAttachmentRecord> APP_ATTACHMENT_DATA__FK_APP_ATTACHMENT_DATA_ATTACHMENT_ID = ForeignKeys0.APP_ATTACHMENT_DATA__FK_APP_ATTACHMENT_DATA_ATTACHMENT_ID;
    public static final ForeignKey<AppUserConfigRecord, AppUserRecord> APP_USER_CONFIG__FK_APP_USER_CONFIG_USER_ID = ForeignKeys0.APP_USER_CONFIG__FK_APP_USER_CONFIG_USER_ID;
    public static final ForeignKey<AppUserConfigRecord, AppAttachmentRecord> APP_USER_CONFIG__FK_APP_USER_CONFIG_ATTACHMENT_ID = ForeignKeys0.APP_USER_CONFIG__FK_APP_USER_CONFIG_ATTACHMENT_ID;
    public static final ForeignKey<AppVersionRecord, AppUserRecord> APP_VERSION__FK_APP_VERSION_OWNER_ID = ForeignKeys0.APP_VERSION__FK_APP_VERSION_OWNER_ID;
    public static final ForeignKey<BazRecord, AppUserRecord> BAZ__FK_BAZ_OWNER_ID = ForeignKeys0.BAZ__FK_BAZ_OWNER_ID;
    public static final ForeignKey<BazLinkRecord, BazRecord> BAZ_LINK__FK_BAZ_LINK_BAZ_ID = ForeignKeys0.BAZ_LINK__FK_BAZ_LINK_BAZ_ID;
    public static final ForeignKey<BazLinkRecord, BazValueRecord> BAZ_LINK__FK_BAZ_LINK_VALUE_ID = ForeignKeys0.BAZ_LINK__FK_BAZ_LINK_VALUE_ID;
    public static final ForeignKey<CorgeRecord, CorgeTypeRecord> CORGE__FK_CORGE_TYPE_ID = ForeignKeys0.CORGE__FK_CORGE_TYPE_ID;
    public static final ForeignKey<CorgeRecord, AppUserRecord> CORGE__FK_CORGE_OWNER_ID = ForeignKeys0.CORGE__FK_CORGE_OWNER_ID;
    public static final ForeignKey<CorgeRecord, CorgeTypeRecord> CORGE__FK_CORGE_TYPE2 = ForeignKeys0.CORGE__FK_CORGE_TYPE2;
    public static final ForeignKey<CorgeLinkRecord, CorgeRecord> CORGE_LINK__FK_CORGE_LINK_CORGE = ForeignKeys0.CORGE_LINK__FK_CORGE_LINK_CORGE;
    public static final ForeignKey<CorgeLinkRecord, CorgeAssocRecord> CORGE_LINK__FK_CORGE_LINK_ASSOC = ForeignKeys0.CORGE_LINK__FK_CORGE_LINK_ASSOC;
    public static final ForeignKey<FooRecord, FooTypeRecord> FOO__FK_FOO_TYPE_ID = ForeignKeys0.FOO__FK_FOO_TYPE_ID;
    public static final ForeignKey<FooRecord, AppUserRecord> FOO__FK_FOO_OWNER_ID = ForeignKeys0.FOO__FK_FOO_OWNER_ID;
    public static final ForeignKey<GraultRecord, AppAttachmentRecord> GRAULT__FK_GRAULT_ATTACHMENT_ID = ForeignKeys0.GRAULT__FK_GRAULT_ATTACHMENT_ID;
    public static final ForeignKey<GridColumnsRecord, AppUserRecord> GRID_COLUMNS__FK_GRID_COLUMNS_OWNER_ID = ForeignKeys0.GRID_COLUMNS__FK_GRID_COLUMNS_OWNER_ID;
    public static final ForeignKey<MetaConfigRecord, FooTypeRecord> META_CONFIG__FK_META_CONFIG_TYPE_ID = ForeignKeys0.META_CONFIG__FK_META_CONFIG_TYPE_ID;
    public static final ForeignKey<MetaConfigRecord, AppAttachmentRecord> META_CONFIG__FK_META_CONFIG_ATTACHMENT_ID = ForeignKeys0.META_CONFIG__FK_META_CONFIG_ATTACHMENT_ID;
    public static final ForeignKey<MetaConfigRecord, CorgeTypeRecord> META_CONFIG__FK_META_CONFIG_CORGE_TYPE_ID = ForeignKeys0.META_CONFIG__FK_META_CONFIG_CORGE_TYPE_ID;
    public static final ForeignKey<NodeRecord, NodeRecord> NODE__FK_NODE_PARENT_ID = ForeignKeys0.NODE__FK_NODE_PARENT_ID;
    public static final ForeignKey<PlughRecord, AppUserRecord> PLUGH__FK_PLUGH_OWNER_ID = ForeignKeys0.PLUGH__FK_PLUGH_OWNER_ID;
    public static final ForeignKey<QuxMainRecord, QuxARecord> QUX_MAIN__FK_QUX_A_ID = ForeignKeys0.QUX_MAIN__FK_QUX_A_ID;
    public static final ForeignKey<QuxMainRecord, QuxBRecord> QUX_MAIN__FK_QUX_B_NAME = ForeignKeys0.QUX_MAIN__FK_QUX_B_NAME;
    public static final ForeignKey<QuxMainRecord, QuxCRecord> QUX_MAIN__FK_QUX_C_ID1 = ForeignKeys0.QUX_MAIN__FK_QUX_C_ID1;
    public static final ForeignKey<QuxMainRecord, QuxCRecord> QUX_MAIN__FK_QUX_C_ID2 = ForeignKeys0.QUX_MAIN__FK_QUX_C_ID2;
    public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D_ID = ForeignKeys0.QUX_MAIN__FK_QUX_D_ID;
    public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D2_ID = ForeignKeys0.QUX_MAIN__FK_QUX_D2_ID;
    public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D3_ID = ForeignKeys0.QUX_MAIN__FK_QUX_D3_ID;
    public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D4_ID = ForeignKeys0.QUX_MAIN__FK_QUX_D4_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AppAttachmentRecord> PK_APP_ATTACHMENT = Internal.createUniqueKey(AppAttachment.APP_ATTACHMENT, "pk_app_attachment", AppAttachment.APP_ATTACHMENT.ID);
        public static final UniqueKey<AppAttachmentDataRecord> PK_APP_ATTACHMENT_DATA = Internal.createUniqueKey(AppAttachmentData.APP_ATTACHMENT_DATA, "pk_app_attachment_data", AppAttachmentData.APP_ATTACHMENT_DATA.ID);
        public static final UniqueKey<AppAttachmentDataRecord> UC_APP_ATTACHMENT_DATA_ATTACHMENT_ID = Internal.createUniqueKey(AppAttachmentData.APP_ATTACHMENT_DATA, "uc_app_attachment_data_attachment_id", AppAttachmentData.APP_ATTACHMENT_DATA.ATTACHMENT_ID);
        public static final UniqueKey<AppConfigRecord> PK_APP_CONFIG = Internal.createUniqueKey(AppConfig.APP_CONFIG, "pk_app_config", AppConfig.APP_CONFIG.NAME);
        public static final UniqueKey<AppLoginRecord> PK_APP_LOGIN = Internal.createUniqueKey(AppLogin.APP_LOGIN, "pk_app_login", AppLogin.APP_LOGIN.SERIES);
        public static final UniqueKey<AppTranslationRecord> PK_APP_TRANSLATION = Internal.createUniqueKey(AppTranslation.APP_TRANSLATION, "pk_app_translation", AppTranslation.APP_TRANSLATION.ID);
        public static final UniqueKey<AppTranslationRecord> UC_APP_TRANSLATION = Internal.createUniqueKey(AppTranslation.APP_TRANSLATION, "uc_app_translation", AppTranslation.APP_TRANSLATION.LOCALE, AppTranslation.APP_TRANSLATION.TAG, AppTranslation.APP_TRANSLATION.PROCESS_NAME);
        public static final UniqueKey<AppUserRecord> PK_APP_USER = Internal.createUniqueKey(AppUser.APP_USER, "pk_app_user", AppUser.APP_USER.ID);
        public static final UniqueKey<AppUserRecord> UC_APP_USER_LOGIN = Internal.createUniqueKey(AppUser.APP_USER, "uc_app_user_login", AppUser.APP_USER.LOGIN);
        public static final UniqueKey<AppUserConfigRecord> PK_APP_USER_CONFIG = Internal.createUniqueKey(AppUserConfig.APP_USER_CONFIG, "pk_app_user_config", AppUserConfig.APP_USER_CONFIG.LOGIN);
        public static final UniqueKey<AppVersionRecord> PK_APP_VERSION = Internal.createUniqueKey(AppVersion.APP_VERSION, "pk_app_version", AppVersion.APP_VERSION.ID);
        public static final UniqueKey<BazRecord> PK_BAZ = Internal.createUniqueKey(Baz.BAZ, "pk_baz", Baz.BAZ.ID);
        public static final UniqueKey<BazLinkRecord> PK_BAZ_LINK = Internal.createUniqueKey(BazLink.BAZ_LINK, "pk_baz_link", BazLink.BAZ_LINK.ID);
        public static final UniqueKey<BazLinkRecord> BAZ_LINK_BAZ_ID_VALUE_ID_KEY = Internal.createUniqueKey(BazLink.BAZ_LINK, "baz_link_baz_id_value_id_key", BazLink.BAZ_LINK.BAZ_ID, BazLink.BAZ_LINK.VALUE_ID);
        public static final UniqueKey<BazValueRecord> PK_BAZ_VALUE = Internal.createUniqueKey(BazValue.BAZ_VALUE, "pk_baz_value", BazValue.BAZ_VALUE.ID);
        public static final UniqueKey<CorgeRecord> PK_CORGE = Internal.createUniqueKey(Corge.CORGE, "pk_corge", Corge.CORGE.ID);
        public static final UniqueKey<CorgeAssocRecord> PK_CORGE_ASSOC = Internal.createUniqueKey(CorgeAssoc.CORGE_ASSOC, "pk_corge_assoc", CorgeAssoc.CORGE_ASSOC.ID);
        public static final UniqueKey<CorgeLinkRecord> PK_CORGE_LINK = Internal.createUniqueKey(CorgeLink.CORGE_LINK, "pk_corge_link", CorgeLink.CORGE_LINK.ID);
        public static final UniqueKey<CorgeTypeRecord> PK_CORGE_TYPE = Internal.createUniqueKey(CorgeType.CORGE_TYPE, "pk_corge_type", CorgeType.CORGE_TYPE.ID);
        public static final UniqueKey<FooRecord> PK_FOO = Internal.createUniqueKey(Foo.FOO, "pk_foo", Foo.FOO.ID);
        public static final UniqueKey<FooTypeRecord> PK_FOO_TYPE = Internal.createUniqueKey(FooType.FOO_TYPE, "pk_foo_type", FooType.FOO_TYPE.ORDINAL);
        public static final UniqueKey<FooTypeRecord> FOO_TYPE_NAME_KEY = Internal.createUniqueKey(FooType.FOO_TYPE, "foo_type_name_key", FooType.FOO_TYPE.NAME);
        public static final UniqueKey<GarplyRecord> PK_GARPLY = Internal.createUniqueKey(Garply.GARPLY, "pk_garply", Garply.GARPLY.ID);
        public static final UniqueKey<GraultRecord> PK_GRAULT = Internal.createUniqueKey(Grault.GRAULT, "pk_grault", Grault.GRAULT.ID);
        public static final UniqueKey<GridColumnsRecord> PK_GRID_COLUMNS = Internal.createUniqueKey(GridColumns.GRID_COLUMNS, "pk_grid_columns", GridColumns.GRID_COLUMNS.ID);
        public static final UniqueKey<GridColumnsRecord> GRID_COLUMNS_NAME_OWNER_ID_KEY = Internal.createUniqueKey(GridColumns.GRID_COLUMNS, "grid_columns_name_owner_id_key", GridColumns.GRID_COLUMNS.NAME, GridColumns.GRID_COLUMNS.OWNER_ID);
        public static final UniqueKey<MetaConfigRecord> PK_META_CONFIG = Internal.createUniqueKey(MetaConfig.META_CONFIG, "pk_meta_config", MetaConfig.META_CONFIG.ID);
        public static final UniqueKey<NodeRecord> PK_NODE = Internal.createUniqueKey(Node.NODE, "pk_node", Node.NODE.ID);
        public static final UniqueKey<NodeRecord> UC_NODE_NAME = Internal.createUniqueKey(Node.NODE, "uc_node_name", Node.NODE.NAME);
        public static final UniqueKey<PlughRecord> PK_PLUGH = Internal.createUniqueKey(Plugh.PLUGH, "pk_plugh", Plugh.PLUGH.ID);
        public static final UniqueKey<QuxARecord> PK_QUX_A = Internal.createUniqueKey(QuxA.QUX_A, "pk_qux_a", QuxA.QUX_A.ID);
        public static final UniqueKey<QuxARecord> QUX_A_NAME_KEY = Internal.createUniqueKey(QuxA.QUX_A, "qux_a_name_key", QuxA.QUX_A.NAME);
        public static final UniqueKey<QuxBRecord> PK_QUX_B = Internal.createUniqueKey(QuxB.QUX_B, "pk_qux_b", QuxB.QUX_B.ID);
        public static final UniqueKey<QuxBRecord> QUX_B_NAME_KEY = Internal.createUniqueKey(QuxB.QUX_B, "qux_b_name_key", QuxB.QUX_B.NAME);
        public static final UniqueKey<QuxCRecord> PK_QUX_C = Internal.createUniqueKey(QuxC.QUX_C, "pk_qux_c", QuxC.QUX_C.ID);
        public static final UniqueKey<QuxCRecord> QUX_C_NAME_KEY = Internal.createUniqueKey(QuxC.QUX_C, "qux_c_name_key", QuxC.QUX_C.NAME);
        public static final UniqueKey<QuxDRecord> PK_QUX_D = Internal.createUniqueKey(QuxD.QUX_D, "pk_qux_d", QuxD.QUX_D.ID);
        public static final UniqueKey<QuxDRecord> QUX_D_NAME_KEY = Internal.createUniqueKey(QuxD.QUX_D, "qux_d_name_key", QuxD.QUX_D.NAME);
        public static final UniqueKey<QuxMainRecord> PK_QUX_MAIN = Internal.createUniqueKey(QuxMain.QUX_MAIN, "pk_qux_main", QuxMain.QUX_MAIN.ID);
        public static final UniqueKey<WaldoRecord> PK_WALDO = Internal.createUniqueKey(Waldo.WALDO, "pk_waldo", Waldo.WALDO.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AppAttachmentDataRecord, AppAttachmentRecord> APP_ATTACHMENT_DATA__FK_APP_ATTACHMENT_DATA_ATTACHMENT_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_ATTACHMENT, AppAttachmentData.APP_ATTACHMENT_DATA, "app_attachment_data__fk_app_attachment_data_attachment_id", AppAttachmentData.APP_ATTACHMENT_DATA.ATTACHMENT_ID);
        public static final ForeignKey<AppUserConfigRecord, AppUserRecord> APP_USER_CONFIG__FK_APP_USER_CONFIG_USER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, AppUserConfig.APP_USER_CONFIG, "app_user_config__fk_app_user_config_user_id", AppUserConfig.APP_USER_CONFIG.USER_ID);
        public static final ForeignKey<AppUserConfigRecord, AppAttachmentRecord> APP_USER_CONFIG__FK_APP_USER_CONFIG_ATTACHMENT_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_ATTACHMENT, AppUserConfig.APP_USER_CONFIG, "app_user_config__fk_app_user_config_attachment_id", AppUserConfig.APP_USER_CONFIG.ATTACHMENT_ID);
        public static final ForeignKey<AppVersionRecord, AppUserRecord> APP_VERSION__FK_APP_VERSION_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, AppVersion.APP_VERSION, "app_version__fk_app_version_owner_id", AppVersion.APP_VERSION.OWNER_ID);
        public static final ForeignKey<BazRecord, AppUserRecord> BAZ__FK_BAZ_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, Baz.BAZ, "baz__fk_baz_owner_id", Baz.BAZ.OWNER_ID);
        public static final ForeignKey<BazLinkRecord, BazRecord> BAZ_LINK__FK_BAZ_LINK_BAZ_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_BAZ, BazLink.BAZ_LINK, "baz_link__fk_baz_link_baz_id", BazLink.BAZ_LINK.BAZ_ID);
        public static final ForeignKey<BazLinkRecord, BazValueRecord> BAZ_LINK__FK_BAZ_LINK_VALUE_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_BAZ_VALUE, BazLink.BAZ_LINK, "baz_link__fk_baz_link_value_id", BazLink.BAZ_LINK.VALUE_ID);
        public static final ForeignKey<CorgeRecord, CorgeTypeRecord> CORGE__FK_CORGE_TYPE_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_CORGE_TYPE, Corge.CORGE, "corge__fk_corge_type_id", Corge.CORGE.TYPE_ID);
        public static final ForeignKey<CorgeRecord, AppUserRecord> CORGE__FK_CORGE_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, Corge.CORGE, "corge__fk_corge_owner_id", Corge.CORGE.OWNER_ID);
        public static final ForeignKey<CorgeRecord, CorgeTypeRecord> CORGE__FK_CORGE_TYPE2 = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_CORGE_TYPE, Corge.CORGE, "corge__fk_corge_type2", Corge.CORGE.TYPE2);
        public static final ForeignKey<CorgeLinkRecord, CorgeRecord> CORGE_LINK__FK_CORGE_LINK_CORGE = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_CORGE, CorgeLink.CORGE_LINK, "corge_link__fk_corge_link_corge", CorgeLink.CORGE_LINK.CORGE_ID);
        public static final ForeignKey<CorgeLinkRecord, CorgeAssocRecord> CORGE_LINK__FK_CORGE_LINK_ASSOC = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_CORGE_ASSOC, CorgeLink.CORGE_LINK, "corge_link__fk_corge_link_assoc", CorgeLink.CORGE_LINK.ASSOC_ID);
        public static final ForeignKey<FooRecord, FooTypeRecord> FOO__FK_FOO_TYPE_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.FOO_TYPE_NAME_KEY, Foo.FOO, "foo__fk_foo_type_id", Foo.FOO.TYPE);
        public static final ForeignKey<FooRecord, AppUserRecord> FOO__FK_FOO_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, Foo.FOO, "foo__fk_foo_owner_id", Foo.FOO.OWNER_ID);
        public static final ForeignKey<GraultRecord, AppAttachmentRecord> GRAULT__FK_GRAULT_ATTACHMENT_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_ATTACHMENT, Grault.GRAULT, "grault__fk_grault_attachment_id", Grault.GRAULT.ATTACHMENT_ID);
        public static final ForeignKey<GridColumnsRecord, AppUserRecord> GRID_COLUMNS__FK_GRID_COLUMNS_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, GridColumns.GRID_COLUMNS, "grid_columns__fk_grid_columns_owner_id", GridColumns.GRID_COLUMNS.OWNER_ID);
        public static final ForeignKey<MetaConfigRecord, FooTypeRecord> META_CONFIG__FK_META_CONFIG_TYPE_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.FOO_TYPE_NAME_KEY, MetaConfig.META_CONFIG, "meta_config__fk_meta_config_type_id", MetaConfig.META_CONFIG.TYPE);
        public static final ForeignKey<MetaConfigRecord, AppAttachmentRecord> META_CONFIG__FK_META_CONFIG_ATTACHMENT_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_ATTACHMENT, MetaConfig.META_CONFIG, "meta_config__fk_meta_config_attachment_id", MetaConfig.META_CONFIG.ATTACHMENT_ID);
        public static final ForeignKey<MetaConfigRecord, CorgeTypeRecord> META_CONFIG__FK_META_CONFIG_CORGE_TYPE_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_CORGE_TYPE, MetaConfig.META_CONFIG, "meta_config__fk_meta_config_corge_type_id", MetaConfig.META_CONFIG.CORGE_TYPE_ID);
        public static final ForeignKey<NodeRecord, NodeRecord> NODE__FK_NODE_PARENT_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_NODE, Node.NODE, "node__fk_node_parent_id", Node.NODE.PARENT_ID);
        public static final ForeignKey<PlughRecord, AppUserRecord> PLUGH__FK_PLUGH_OWNER_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_APP_USER, Plugh.PLUGH, "plugh__fk_plugh_owner_id", Plugh.PLUGH.OWNER_ID);
        public static final ForeignKey<QuxMainRecord, QuxARecord> QUX_MAIN__FK_QUX_A_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_A, QuxMain.QUX_MAIN, "qux_main__fk_qux_a_id", QuxMain.QUX_MAIN.QUX_A_ID);
        public static final ForeignKey<QuxMainRecord, QuxBRecord> QUX_MAIN__FK_QUX_B_NAME = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.QUX_B_NAME_KEY, QuxMain.QUX_MAIN, "qux_main__fk_qux_b_name", QuxMain.QUX_MAIN.QUX_B_NAME);
        public static final ForeignKey<QuxMainRecord, QuxCRecord> QUX_MAIN__FK_QUX_C_ID1 = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_C, QuxMain.QUX_MAIN, "qux_main__fk_qux_c_id1", QuxMain.QUX_MAIN.QUX_C_ID1);
        public static final ForeignKey<QuxMainRecord, QuxCRecord> QUX_MAIN__FK_QUX_C_ID2 = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_C, QuxMain.QUX_MAIN, "qux_main__fk_qux_c_id2", QuxMain.QUX_MAIN.QUX_C_ID2);
        public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_D, QuxMain.QUX_MAIN, "qux_main__fk_qux_d_id", QuxMain.QUX_MAIN.QUX_D_ID);
        public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D2_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_D, QuxMain.QUX_MAIN, "qux_main__fk_qux_d2_id", QuxMain.QUX_MAIN.QUX_D2_ID);
        public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D3_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_D, QuxMain.QUX_MAIN, "qux_main__fk_qux_d3_id", QuxMain.QUX_MAIN.QUX_D3_ID);
        public static final ForeignKey<QuxMainRecord, QuxDRecord> QUX_MAIN__FK_QUX_D4_ID = Internal.createForeignKey(de.quinscape.automatontest.domain.Keys.PK_QUX_D, QuxMain.QUX_MAIN, "qux_main__fk_qux_d4_id", QuxMain.QUX_MAIN.QUX_D4_ID);
    }
}
