/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain;


import de.quinscape.automatontest.domain.tables.AppAttachment;
import de.quinscape.automatontest.domain.tables.AppAttachmentData;
import de.quinscape.automatontest.domain.tables.AppConfig;
import de.quinscape.automatontest.domain.tables.AppLogin;
import de.quinscape.automatontest.domain.tables.AppTranslation;
import de.quinscape.automatontest.domain.tables.AppUser;
import de.quinscape.automatontest.domain.tables.AppUserConfig;
import de.quinscape.automatontest.domain.tables.AppVersion;
import de.quinscape.automatontest.domain.tables.Bar;
import de.quinscape.automatontest.domain.tables.Baz;
import de.quinscape.automatontest.domain.tables.BazLink;
import de.quinscape.automatontest.domain.tables.BazValue;
import de.quinscape.automatontest.domain.tables.Corge;
import de.quinscape.automatontest.domain.tables.CorgeAssoc;
import de.quinscape.automatontest.domain.tables.CorgeLink;
import de.quinscape.automatontest.domain.tables.CorgeType;
import de.quinscape.automatontest.domain.tables.Foo;
import de.quinscape.automatontest.domain.tables.FooType;
import de.quinscape.automatontest.domain.tables.Garply;
import de.quinscape.automatontest.domain.tables.Grault;
import de.quinscape.automatontest.domain.tables.GridColumns;
import de.quinscape.automatontest.domain.tables.MetaConfig;
import de.quinscape.automatontest.domain.tables.Node;
import de.quinscape.automatontest.domain.tables.Plugh;
import de.quinscape.automatontest.domain.tables.QuxA;
import de.quinscape.automatontest.domain.tables.QuxB;
import de.quinscape.automatontest.domain.tables.QuxC;
import de.quinscape.automatontest.domain.tables.QuxD;
import de.quinscape.automatontest.domain.tables.QuxE;
import de.quinscape.automatontest.domain.tables.QuxMain;
import de.quinscape.automatontest.domain.tables.QuxMid;
import de.quinscape.automatontest.domain.tables.QuxTop;
import de.quinscape.automatontest.domain.tables.SumPerMonth;
import de.quinscape.automatontest.domain.tables.Waldo;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_attachment</code>.
     */
    public static final AppAttachment APP_ATTACHMENT = AppAttachment.APP_ATTACHMENT;

    /**
     * The table <code>public.app_attachment_data</code>.
     */
    public static final AppAttachmentData APP_ATTACHMENT_DATA = AppAttachmentData.APP_ATTACHMENT_DATA;

    /**
     * The table <code>public.app_config</code>.
     */
    public static final AppConfig APP_CONFIG = AppConfig.APP_CONFIG;

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_translation</code>.
     */
    public static final AppTranslation APP_TRANSLATION = AppTranslation.APP_TRANSLATION;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.app_user_config</code>.
     */
    public static final AppUserConfig APP_USER_CONFIG = AppUserConfig.APP_USER_CONFIG;

    /**
     * The table <code>public.app_version</code>.
     */
    public static final AppVersion APP_VERSION = AppVersion.APP_VERSION;

    /**
     * The table <code>public.bar</code>.
     */
    public static final Bar BAR = Bar.BAR;

    /**
     * The table <code>public.baz</code>.
     */
    public static final Baz BAZ = Baz.BAZ;

    /**
     * The table <code>public.baz_link</code>.
     */
    public static final BazLink BAZ_LINK = BazLink.BAZ_LINK;

    /**
     * The table <code>public.baz_value</code>.
     */
    public static final BazValue BAZ_VALUE = BazValue.BAZ_VALUE;

    /**
     * The table <code>public.corge</code>.
     */
    public static final Corge CORGE = Corge.CORGE;

    /**
     * The table <code>public.corge_assoc</code>.
     */
    public static final CorgeAssoc CORGE_ASSOC = CorgeAssoc.CORGE_ASSOC;

    /**
     * The table <code>public.corge_link</code>.
     */
    public static final CorgeLink CORGE_LINK = CorgeLink.CORGE_LINK;

    /**
     * The table <code>public.corge_type</code>.
     */
    public static final CorgeType CORGE_TYPE = CorgeType.CORGE_TYPE;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public static final FooType FOO_TYPE = FooType.FOO_TYPE;

    /**
     * The table <code>public.garply</code>.
     */
    public static final Garply GARPLY = Garply.GARPLY;

    /**
     * The table <code>public.grault</code>.
     */
    public static final Grault GRAULT = Grault.GRAULT;

    /**
     * The table <code>public.grid_columns</code>.
     */
    public static final GridColumns GRID_COLUMNS = GridColumns.GRID_COLUMNS;

    /**
     * The table <code>public.meta_config</code>.
     */
    public static final MetaConfig META_CONFIG = MetaConfig.META_CONFIG;

    /**
     * The table <code>public.node</code>.
     */
    public static final Node NODE = Node.NODE;

    /**
     * The table <code>public.plugh</code>.
     */
    public static final Plugh PLUGH = Plugh.PLUGH;

    /**
     * The table <code>public.qux_a</code>.
     */
    public static final QuxA QUX_A = QuxA.QUX_A;

    /**
     * The table <code>public.qux_b</code>.
     */
    public static final QuxB QUX_B = QuxB.QUX_B;

    /**
     * The table <code>public.qux_c</code>.
     */
    public static final QuxC QUX_C = QuxC.QUX_C;

    /**
     * The table <code>public.qux_d</code>.
     */
    public static final QuxD QUX_D = QuxD.QUX_D;

    /**
     * The table <code>public.qux_e</code>.
     */
    public static final QuxE QUX_E = QuxE.QUX_E;

    /**
     * The table <code>public.qux_main</code>.
     */
    public static final QuxMain QUX_MAIN = QuxMain.QUX_MAIN;

    /**
     * The table <code>public.qux_mid</code>.
     */
    public static final QuxMid QUX_MID = QuxMid.QUX_MID;

    /**
     * The table <code>public.qux_top</code>.
     */
    public static final QuxTop QUX_TOP = QuxTop.QUX_TOP;

    /**
     * The table <code>public.sum_per_month</code>.
     */
    public static final SumPerMonth SUM_PER_MONTH = SumPerMonth.SUM_PER_MONTH;

    /**
     * The table <code>public.waldo</code>.
     */
    public static final Waldo WALDO = Waldo.WALDO;
}
