/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain;


import de.quinscape.automatontest.domain.tables.AppAttachment;
import de.quinscape.automatontest.domain.tables.AppAttachmentData;
import de.quinscape.automatontest.domain.tables.AppConfig;
import de.quinscape.automatontest.domain.tables.AppLogin;
import de.quinscape.automatontest.domain.tables.AppTranslation;
import de.quinscape.automatontest.domain.tables.AppUser;
import de.quinscape.automatontest.domain.tables.AppUserConfig;
import de.quinscape.automatontest.domain.tables.AppVersion;
import de.quinscape.automatontest.domain.tables.Bar;
import de.quinscape.automatontest.domain.tables.Baz;
import de.quinscape.automatontest.domain.tables.BazLink;
import de.quinscape.automatontest.domain.tables.BazValue;
import de.quinscape.automatontest.domain.tables.Corge;
import de.quinscape.automatontest.domain.tables.CorgeAssoc;
import de.quinscape.automatontest.domain.tables.CorgeLink;
import de.quinscape.automatontest.domain.tables.CorgeType;
import de.quinscape.automatontest.domain.tables.Foo;
import de.quinscape.automatontest.domain.tables.FooType;
import de.quinscape.automatontest.domain.tables.Grault;
import de.quinscape.automatontest.domain.tables.GridColumns;
import de.quinscape.automatontest.domain.tables.Node;
import de.quinscape.automatontest.domain.tables.QuxA;
import de.quinscape.automatontest.domain.tables.QuxB;
import de.quinscape.automatontest.domain.tables.QuxC;
import de.quinscape.automatontest.domain.tables.QuxD;
import de.quinscape.automatontest.domain.tables.QuxMain;
import de.quinscape.automatontest.domain.tables.SumPerMonth;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_attachment</code>.
     */
    public static final AppAttachment APP_ATTACHMENT = de.quinscape.automatontest.domain.tables.AppAttachment.APP_ATTACHMENT;

    /**
     * The table <code>public.app_attachment_data</code>.
     */
    public static final AppAttachmentData APP_ATTACHMENT_DATA = de.quinscape.automatontest.domain.tables.AppAttachmentData.APP_ATTACHMENT_DATA;

    /**
     * The table <code>public.app_config</code>.
     */
    public static final AppConfig APP_CONFIG = de.quinscape.automatontest.domain.tables.AppConfig.APP_CONFIG;

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = de.quinscape.automatontest.domain.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_translation</code>.
     */
    public static final AppTranslation APP_TRANSLATION = de.quinscape.automatontest.domain.tables.AppTranslation.APP_TRANSLATION;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = de.quinscape.automatontest.domain.tables.AppUser.APP_USER;

    /**
     * The table <code>public.app_user_config</code>.
     */
    public static final AppUserConfig APP_USER_CONFIG = de.quinscape.automatontest.domain.tables.AppUserConfig.APP_USER_CONFIG;

    /**
     * The table <code>public.app_version</code>.
     */
    public static final AppVersion APP_VERSION = de.quinscape.automatontest.domain.tables.AppVersion.APP_VERSION;

    /**
     * The table <code>public.bar</code>.
     */
    public static final Bar BAR = de.quinscape.automatontest.domain.tables.Bar.BAR;

    /**
     * The table <code>public.baz</code>.
     */
    public static final Baz BAZ = de.quinscape.automatontest.domain.tables.Baz.BAZ;

    /**
     * The table <code>public.baz_link</code>.
     */
    public static final BazLink BAZ_LINK = de.quinscape.automatontest.domain.tables.BazLink.BAZ_LINK;

    /**
     * The table <code>public.baz_value</code>.
     */
    public static final BazValue BAZ_VALUE = de.quinscape.automatontest.domain.tables.BazValue.BAZ_VALUE;

    /**
     * The table <code>public.corge</code>.
     */
    public static final Corge CORGE = de.quinscape.automatontest.domain.tables.Corge.CORGE;

    /**
     * The table <code>public.corge_assoc</code>.
     */
    public static final CorgeAssoc CORGE_ASSOC = de.quinscape.automatontest.domain.tables.CorgeAssoc.CORGE_ASSOC;

    /**
     * The table <code>public.corge_link</code>.
     */
    public static final CorgeLink CORGE_LINK = de.quinscape.automatontest.domain.tables.CorgeLink.CORGE_LINK;

    /**
     * The table <code>public.corge_type</code>.
     */
    public static final CorgeType CORGE_TYPE = de.quinscape.automatontest.domain.tables.CorgeType.CORGE_TYPE;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = de.quinscape.automatontest.domain.tables.Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public static final FooType FOO_TYPE = de.quinscape.automatontest.domain.tables.FooType.FOO_TYPE;

    /**
     * The table <code>public.grault</code>.
     */
    public static final Grault GRAULT = de.quinscape.automatontest.domain.tables.Grault.GRAULT;

    /**
     * The table <code>public.grid_columns</code>.
     */
    public static final GridColumns GRID_COLUMNS = de.quinscape.automatontest.domain.tables.GridColumns.GRID_COLUMNS;

    /**
     * The table <code>public.node</code>.
     */
    public static final Node NODE = de.quinscape.automatontest.domain.tables.Node.NODE;

    /**
     * The table <code>public.qux_a</code>.
     */
    public static final QuxA QUX_A = de.quinscape.automatontest.domain.tables.QuxA.QUX_A;

    /**
     * The table <code>public.qux_b</code>.
     */
    public static final QuxB QUX_B = de.quinscape.automatontest.domain.tables.QuxB.QUX_B;

    /**
     * The table <code>public.qux_c</code>.
     */
    public static final QuxC QUX_C = de.quinscape.automatontest.domain.tables.QuxC.QUX_C;

    /**
     * The table <code>public.qux_d</code>.
     */
    public static final QuxD QUX_D = de.quinscape.automatontest.domain.tables.QuxD.QUX_D;

    /**
     * The table <code>public.qux_main</code>.
     */
    public static final QuxMain QUX_MAIN = de.quinscape.automatontest.domain.tables.QuxMain.QUX_MAIN;

    /**
     * The table <code>public.sum_per_month</code>.
     */
    public static final SumPerMonth SUM_PER_MONTH = de.quinscape.automatontest.domain.tables.SumPerMonth.SUM_PER_MONTH;
}
