/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain;


import de.quinscape.automatontest.domain.tables.Address;
import de.quinscape.automatontest.domain.tables.AppAttachment;
import de.quinscape.automatontest.domain.tables.AppConfig;
import de.quinscape.automatontest.domain.tables.AppLogin;
import de.quinscape.automatontest.domain.tables.AppTranslation;
import de.quinscape.automatontest.domain.tables.AppUser;
import de.quinscape.automatontest.domain.tables.AppUserConfig;
import de.quinscape.automatontest.domain.tables.Customer;
import de.quinscape.automatontest.domain.tables.Foo;
import de.quinscape.automatontest.domain.tables.FooType;
import de.quinscape.automatontest.domain.tables.Order;
import de.quinscape.automatontest.domain.tables.OrderItem;
import de.quinscape.automatontest.domain.tables.OrderStatus;
import de.quinscape.automatontest.domain.tables.Product;
import de.quinscape.automatontest.domain.tables.ShippingType;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = de.quinscape.automatontest.domain.tables.Address.ADDRESS;

    /**
     * The table <code>public.app_attachment</code>.
     */
    public static final AppAttachment APP_ATTACHMENT = de.quinscape.automatontest.domain.tables.AppAttachment.APP_ATTACHMENT;

    /**
     * The table <code>public.app_config</code>.
     */
    public static final AppConfig APP_CONFIG = de.quinscape.automatontest.domain.tables.AppConfig.APP_CONFIG;

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = de.quinscape.automatontest.domain.tables.AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_translation</code>.
     */
    public static final AppTranslation APP_TRANSLATION = de.quinscape.automatontest.domain.tables.AppTranslation.APP_TRANSLATION;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = de.quinscape.automatontest.domain.tables.AppUser.APP_USER;

    /**
     * The table <code>public.app_user_config</code>.
     */
    public static final AppUserConfig APP_USER_CONFIG = de.quinscape.automatontest.domain.tables.AppUserConfig.APP_USER_CONFIG;

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = de.quinscape.automatontest.domain.tables.Customer.CUSTOMER;

    /**
     * The table <code>public.foo</code>.
     */
    public static final Foo FOO = de.quinscape.automatontest.domain.tables.Foo.FOO;

    /**
     * The table <code>public.foo_type</code>.
     */
    public static final FooType FOO_TYPE = de.quinscape.automatontest.domain.tables.FooType.FOO_TYPE;

    /**
     * The table <code>public.order</code>.
     */
    public static final Order ORDER = de.quinscape.automatontest.domain.tables.Order.ORDER;

    /**
     * The table <code>public.order_item</code>.
     */
    public static final OrderItem ORDER_ITEM = de.quinscape.automatontest.domain.tables.OrderItem.ORDER_ITEM;

    /**
     * The table <code>public.order_status</code>.
     */
    public static final OrderStatus ORDER_STATUS = de.quinscape.automatontest.domain.tables.OrderStatus.ORDER_STATUS;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = de.quinscape.automatontest.domain.tables.Product.PRODUCT;

    /**
     * The table <code>public.shipping_type</code>.
     */
    public static final ShippingType SHIPPING_TYPE = de.quinscape.automatontest.domain.tables.ShippingType.SHIPPING_TYPE;
}
