/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.AppAttachment;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "app_attachment",
    schema = "public"
)
public class AppAttachmentRecord extends UpdatableRecordImpl<AppAttachmentRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_attachment.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_attachment.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_attachment.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_attachment.description</code>.
     */
    @Column(name = "description")
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_attachment.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_attachment.type</code>.
     */
    @Column(name = "type", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_attachment.url</code>.
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_attachment.url</code>.
     */
    @Column(name = "url", length = 255)
    @Size(max = 255)
    public String getUrl() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AppAttachment.APP_ATTACHMENT.ID;
    }

    @Override
    public Field<String> field2() {
        return AppAttachment.APP_ATTACHMENT.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return AppAttachment.APP_ATTACHMENT.TYPE;
    }

    @Override
    public Field<String> field4() {
        return AppAttachment.APP_ATTACHMENT.URL;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getUrl();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getUrl();
    }

    @Override
    public AppAttachmentRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AppAttachmentRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AppAttachmentRecord value3(String value) {
        setType(value);
        return this;
    }

    @Override
    public AppAttachmentRecord value4(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public AppAttachmentRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppAttachmentRecord
     */
    public AppAttachmentRecord() {
        super(AppAttachment.APP_ATTACHMENT);
    }

    /**
     * Create a detached, initialised AppAttachmentRecord
     */
    public AppAttachmentRecord(String id, String description, String type, String url) {
        super(AppAttachment.APP_ATTACHMENT);

        setId(id);
        setDescription(description);
        setType(type);
        setUrl(url);
    }

    /**
     * Create a detached, initialised AppAttachmentRecord
     */
    public AppAttachmentRecord(de.quinscape.automatontest.domain.tables.pojos.AppAttachment value) {
        super(AppAttachment.APP_ATTACHMENT);

        if (value != null) {
            setId(value.getId());
            setDescription(value.getDescription());
            setType(value.getType());
            setUrl(value.getUrl());
        }
    }
}
