/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.CorgeLink;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "corge_link",
    schema = "public"
)
public class CorgeLinkRecord extends UpdatableRecordImpl<CorgeLinkRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.corge_link.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.corge_link.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.corge_link.version</code>.
     */
    public void setVersion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.corge_link.version</code>.
     */
    @Column(name = "version", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getVersion() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.corge_link.corge_id</code>.
     */
    public void setCorgeId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.corge_link.corge_id</code>.
     */
    @Column(name = "corge_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getCorgeId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.corge_link.assoc_id</code>.
     */
    public void setAssocId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.corge_link.assoc_id</code>.
     */
    @Column(name = "assoc_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getAssocId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CorgeLink.CORGE_LINK.ID;
    }

    @Override
    public Field<String> field2() {
        return CorgeLink.CORGE_LINK.VERSION;
    }

    @Override
    public Field<String> field3() {
        return CorgeLink.CORGE_LINK.CORGE_ID;
    }

    @Override
    public Field<String> field4() {
        return CorgeLink.CORGE_LINK.ASSOC_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getVersion();
    }

    @Override
    public String component3() {
        return getCorgeId();
    }

    @Override
    public String component4() {
        return getAssocId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getVersion();
    }

    @Override
    public String value3() {
        return getCorgeId();
    }

    @Override
    public String value4() {
        return getAssocId();
    }

    @Override
    public CorgeLinkRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public CorgeLinkRecord value2(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public CorgeLinkRecord value3(String value) {
        setCorgeId(value);
        return this;
    }

    @Override
    public CorgeLinkRecord value4(String value) {
        setAssocId(value);
        return this;
    }

    @Override
    public CorgeLinkRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorgeLinkRecord
     */
    public CorgeLinkRecord() {
        super(CorgeLink.CORGE_LINK);
    }

    /**
     * Create a detached, initialised CorgeLinkRecord
     */
    public CorgeLinkRecord(String id, String version, String corgeId, String assocId) {
        super(CorgeLink.CORGE_LINK);

        setId(id);
        setVersion(version);
        setCorgeId(corgeId);
        setAssocId(assocId);
    }

    /**
     * Create a detached, initialised CorgeLinkRecord
     */
    public CorgeLinkRecord(de.quinscape.automatontest.domain.tables.pojos.CorgeLink value) {
        super(CorgeLink.CORGE_LINK);

        if (value != null) {
            setId(value.getId());
            setVersion(value.getVersion());
            setCorgeId(value.getCorgeId());
            setAssocId(value.getAssocId());
        }
    }
}
