/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.Garply;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "garply",
    schema = "public"
)
public class GarplyRecord extends UpdatableRecordImpl<GarplyRecord> implements Record4<String, String, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.garply.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.garply.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.garply.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.garply.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.garply.value</code>.
     */
    public void setValue(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.garply.value</code>.
     */
    @Column(name = "value", nullable = false, precision = 19, scale = 2)
    @NotNull
    public BigDecimal getValue() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.garply.opt</code>.
     */
    public void setOpt(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.garply.opt</code>.
     */
    @Column(name = "opt", precision = 19, scale = 2)
    public BigDecimal getOpt() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, BigDecimal, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, BigDecimal, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Garply.GARPLY.ID;
    }

    @Override
    public Field<String> field2() {
        return Garply.GARPLY.NAME;
    }

    @Override
    public Field<BigDecimal> field3() {
        return Garply.GARPLY.VALUE;
    }

    @Override
    public Field<BigDecimal> field4() {
        return Garply.GARPLY.OPT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public BigDecimal component3() {
        return getValue();
    }

    @Override
    public BigDecimal component4() {
        return getOpt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public BigDecimal value3() {
        return getValue();
    }

    @Override
    public BigDecimal value4() {
        return getOpt();
    }

    @Override
    public GarplyRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public GarplyRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GarplyRecord value3(BigDecimal value) {
        setValue(value);
        return this;
    }

    @Override
    public GarplyRecord value4(BigDecimal value) {
        setOpt(value);
        return this;
    }

    @Override
    public GarplyRecord values(String value1, String value2, BigDecimal value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GarplyRecord
     */
    public GarplyRecord() {
        super(Garply.GARPLY);
    }

    /**
     * Create a detached, initialised GarplyRecord
     */
    public GarplyRecord(String id, String name, BigDecimal value, BigDecimal opt) {
        super(Garply.GARPLY);

        setId(id);
        setName(name);
        setValue(value);
        setOpt(opt);
    }

    /**
     * Create a detached, initialised GarplyRecord
     */
    public GarplyRecord(de.quinscape.automatontest.domain.tables.pojos.Garply value) {
        super(Garply.GARPLY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setValue(value.getValue());
            setOpt(value.getOpt());
        }
    }
}
