/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.GridColumns;
import de.quinscape.domainql.jsonb.JSONB;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "grid_columns",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "grid_columns_name_owner_id_key", columnNames = { "name", "owner_id" })
    }
)
public class GridColumnsRecord extends UpdatableRecordImpl<GridColumnsRecord> implements Record4<String, String, JSONB, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.grid_columns.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.grid_columns.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.grid_columns.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.grid_columns.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.grid_columns.columns</code>.
     */
    public void setColumns(JSONB value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.grid_columns.columns</code>.
     */
    @Column(name = "columns")
    public JSONB getColumns() {
        return (JSONB) get(2);
    }

    /**
     * Setter for <code>public.grid_columns.owner_id</code>.
     */
    public void setOwnerId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.grid_columns.owner_id</code>.
     */
    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, JSONB, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, JSONB, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return GridColumns.GRID_COLUMNS.ID;
    }

    @Override
    public Field<String> field2() {
        return GridColumns.GRID_COLUMNS.NAME;
    }

    @Override
    public Field<JSONB> field3() {
        return GridColumns.GRID_COLUMNS.COLUMNS;
    }

    @Override
    public Field<String> field4() {
        return GridColumns.GRID_COLUMNS.OWNER_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public JSONB component3() {
        return getColumns();
    }

    @Override
    public String component4() {
        return getOwnerId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public JSONB value3() {
        return getColumns();
    }

    @Override
    public String value4() {
        return getOwnerId();
    }

    @Override
    public GridColumnsRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public GridColumnsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GridColumnsRecord value3(JSONB value) {
        setColumns(value);
        return this;
    }

    @Override
    public GridColumnsRecord value4(String value) {
        setOwnerId(value);
        return this;
    }

    @Override
    public GridColumnsRecord values(String value1, String value2, JSONB value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GridColumnsRecord
     */
    public GridColumnsRecord() {
        super(GridColumns.GRID_COLUMNS);
    }

    /**
     * Create a detached, initialised GridColumnsRecord
     */
    public GridColumnsRecord(String id, String name, JSONB columns, String ownerId) {
        super(GridColumns.GRID_COLUMNS);

        setId(id);
        setName(name);
        setColumns(columns);
        setOwnerId(ownerId);
    }

    /**
     * Create a detached, initialised GridColumnsRecord
     */
    public GridColumnsRecord(de.quinscape.automatontest.domain.tables.pojos.GridColumns value) {
        super(GridColumns.GRID_COLUMNS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setColumns(value.getColumns());
            setOwnerId(value.getOwnerId());
        }
    }
}
