/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.Node;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "node",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uc_node_name", columnNames = { "name" })
    }
)
public class NodeRecord extends UpdatableRecordImpl<NodeRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.node.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.node.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.node.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.node.name</code>.
     */
    @Column(name = "name", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.node.parent_id</code>.
     */
    public void setParentId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.node.parent_id</code>.
     */
    @Column(name = "parent_id", length = 36)
    @Size(max = 36)
    public String getParentId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.node.type</code>.
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.node.type</code>.
     */
    @Column(name = "type", nullable = false)
    @NotNull
    public Integer getType() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Node.NODE.ID;
    }

    @Override
    public Field<String> field2() {
        return Node.NODE.NAME;
    }

    @Override
    public Field<String> field3() {
        return Node.NODE.PARENT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Node.NODE.TYPE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getParentId();
    }

    @Override
    public Integer component4() {
        return getType();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getParentId();
    }

    @Override
    public Integer value4() {
        return getType();
    }

    @Override
    public NodeRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public NodeRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public NodeRecord value3(String value) {
        setParentId(value);
        return this;
    }

    @Override
    public NodeRecord value4(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public NodeRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NodeRecord
     */
    public NodeRecord() {
        super(Node.NODE);
    }

    /**
     * Create a detached, initialised NodeRecord
     */
    public NodeRecord(String id, String name, String parentId, Integer type) {
        super(Node.NODE);

        setId(id);
        setName(name);
        setParentId(parentId);
        setType(type);
    }

    /**
     * Create a detached, initialised NodeRecord
     */
    public NodeRecord(de.quinscape.automatontest.domain.tables.pojos.Node value) {
        super(Node.NODE);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setParentId(value.getParentId());
            setType(value.getType());
        }
    }
}
