/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.QuxTop;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "qux_top",
    schema = "public"
)
public class QuxTopRecord extends UpdatableRecordImpl<QuxTopRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.qux_top.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.qux_top.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.qux_top.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.qux_top.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.qux_top.qux_mid_id</code>.
     */
    public void setQuxMidId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.qux_top.qux_mid_id</code>.
     */
    @Column(name = "qux_mid_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getQuxMidId() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return QuxTop.QUX_TOP.ID;
    }

    @Override
    public Field<String> field2() {
        return QuxTop.QUX_TOP.NAME;
    }

    @Override
    public Field<String> field3() {
        return QuxTop.QUX_TOP.QUX_MID_ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getQuxMidId();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getQuxMidId();
    }

    @Override
    public QuxTopRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public QuxTopRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public QuxTopRecord value3(String value) {
        setQuxMidId(value);
        return this;
    }

    @Override
    public QuxTopRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuxTopRecord
     */
    public QuxTopRecord() {
        super(QuxTop.QUX_TOP);
    }

    /**
     * Create a detached, initialised QuxTopRecord
     */
    public QuxTopRecord(String id, String name, String quxMidId) {
        super(QuxTop.QUX_TOP);

        setId(id);
        setName(name);
        setQuxMidId(quxMidId);
    }

    /**
     * Create a detached, initialised QuxTopRecord
     */
    public QuxTopRecord(de.quinscape.automatontest.domain.tables.pojos.QuxTop value) {
        super(QuxTop.QUX_TOP);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setQuxMidId(value.getQuxMidId());
        }
    }
}
