/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.SumPerMonth;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "sum_per_month",
    schema = "public"
)
public class SumPerMonthRecord extends TableRecordImpl<SumPerMonthRecord> implements Record3<Integer, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sum_per_month.month</code>.
     */
    public void setMonth(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sum_per_month.month</code>.
     */
    @Column(name = "month")
    public Integer getMonth() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sum_per_month.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sum_per_month.year</code>.
     */
    @Column(name = "year")
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sum_per_month.sum</code>.
     */
    public void setSum(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sum_per_month.sum</code>.
     */
    @Column(name = "sum")
    public Long getSum() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return SumPerMonth.SUM_PER_MONTH.MONTH;
    }

    @Override
    public Field<Integer> field2() {
        return SumPerMonth.SUM_PER_MONTH.YEAR;
    }

    @Override
    public Field<Long> field3() {
        return SumPerMonth.SUM_PER_MONTH.SUM;
    }

    @Override
    public Integer component1() {
        return getMonth();
    }

    @Override
    public Integer component2() {
        return getYear();
    }

    @Override
    public Long component3() {
        return getSum();
    }

    @Override
    public Integer value1() {
        return getMonth();
    }

    @Override
    public Integer value2() {
        return getYear();
    }

    @Override
    public Long value3() {
        return getSum();
    }

    @Override
    public SumPerMonthRecord value1(Integer value) {
        setMonth(value);
        return this;
    }

    @Override
    public SumPerMonthRecord value2(Integer value) {
        setYear(value);
        return this;
    }

    @Override
    public SumPerMonthRecord value3(Long value) {
        setSum(value);
        return this;
    }

    @Override
    public SumPerMonthRecord values(Integer value1, Integer value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SumPerMonthRecord
     */
    public SumPerMonthRecord() {
        super(SumPerMonth.SUM_PER_MONTH);
    }

    /**
     * Create a detached, initialised SumPerMonthRecord
     */
    public SumPerMonthRecord(Integer month, Integer year, Long sum) {
        super(SumPerMonth.SUM_PER_MONTH);

        setMonth(month);
        setYear(year);
        setSum(sum);
    }

    /**
     * Create a detached, initialised SumPerMonthRecord
     */
    public SumPerMonthRecord(de.quinscape.automatontest.domain.tables.pojos.SumPerMonth value) {
        super(SumPerMonth.SUM_PER_MONTH);

        if (value != null) {
            setMonth(value.getMonth());
            setYear(value.getYear());
            setSum(value.getSum());
        }
    }
}
