/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.records;


import de.quinscape.automatontest.domain.tables.SumPerMonth;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sum_per_month", schema = "public")
public class SumPerMonthRecord extends TableRecordImpl<SumPerMonthRecord> implements Record3<Integer, Integer, Long> {

    private static final long serialVersionUID = -1609939282;

    /**
     * Setter for <code>public.sum_per_month.month</code>.
     */
    public void setMonth(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sum_per_month.month</code>.
     */
    @Column(name = "month", precision = 32)
    public Integer getMonth() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sum_per_month.year</code>.
     */
    public void setYear(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sum_per_month.year</code>.
     */
    @Column(name = "year", precision = 32)
    public Integer getYear() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sum_per_month.sum</code>.
     */
    public void setSum(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sum_per_month.sum</code>.
     */
    @Column(name = "sum", precision = 64)
    public Long getSum() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SumPerMonth.SUM_PER_MONTH.MONTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SumPerMonth.SUM_PER_MONTH.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return SumPerMonth.SUM_PER_MONTH.SUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getSum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMonth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonthRecord value1(Integer value) {
        setMonth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonthRecord value2(Integer value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonthRecord value3(Long value) {
        setSum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonthRecord values(Integer value1, Integer value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SumPerMonthRecord
     */
    public SumPerMonthRecord() {
        super(SumPerMonth.SUM_PER_MONTH);
    }

    /**
     * Create a detached, initialised SumPerMonthRecord
     */
    public SumPerMonthRecord(Integer month, Integer year, Long sum) {
        super(SumPerMonth.SUM_PER_MONTH);

        set(0, month);
        set(1, year);
        set(2, sum);
    }
}
