/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.AppAttachmentDataRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppAttachmentData extends TableImpl<AppAttachmentDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_attachment_data</code>
     */
    public static final AppAttachmentData APP_ATTACHMENT_DATA = new AppAttachmentData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppAttachmentDataRecord> getRecordType() {
        return AppAttachmentDataRecord.class;
    }

    /**
     * The column <code>public.app_attachment_data.id</code>.
     */
    public final TableField<AppAttachmentDataRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_attachment_data.attachment_id</code>.
     */
    public final TableField<AppAttachmentDataRecord, String> ATTACHMENT_ID = createField(DSL.name("attachment_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_attachment_data.data</code>.
     */
    public final TableField<AppAttachmentDataRecord, byte[]> DATA = createField(DSL.name("data"), SQLDataType.BLOB.nullable(false), this, "");

    private AppAttachmentData(Name alias, Table<AppAttachmentDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppAttachmentData(Name alias, Table<AppAttachmentDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.app_attachment_data</code> table reference
     */
    public AppAttachmentData(String alias) {
        this(DSL.name(alias), APP_ATTACHMENT_DATA);
    }

    /**
     * Create an aliased <code>public.app_attachment_data</code> table reference
     */
    public AppAttachmentData(Name alias) {
        this(alias, APP_ATTACHMENT_DATA);
    }

    /**
     * Create a <code>public.app_attachment_data</code> table reference
     */
    public AppAttachmentData() {
        this(DSL.name("app_attachment_data"), null);
    }

    public <O extends Record> AppAttachmentData(Table<O> child, ForeignKey<O, AppAttachmentDataRecord> key) {
        super(child, key, APP_ATTACHMENT_DATA);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppAttachmentDataRecord> getPrimaryKey() {
        return Keys.PK_APP_ATTACHMENT_DATA;
    }

    @Override
    public List<UniqueKey<AppAttachmentDataRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_APP_ATTACHMENT_DATA_ATTACHMENT_ID);
    }

    @Override
    public List<ForeignKey<AppAttachmentDataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.APP_ATTACHMENT_DATA__FK_APP_ATTACHMENT_DATA_ATTACHMENT_ID);
    }

    private transient AppAttachment _appAttachment;

    /**
     * Get the implicit join path to the <code>public.app_attachment</code>
     * table.
     */
    public AppAttachment appAttachment() {
        if (_appAttachment == null)
            _appAttachment = new AppAttachment(this, Keys.APP_ATTACHMENT_DATA__FK_APP_ATTACHMENT_DATA_ATTACHMENT_ID);

        return _appAttachment;
    }

    @Override
    public AppAttachmentData as(String alias) {
        return new AppAttachmentData(DSL.name(alias), this);
    }

    @Override
    public AppAttachmentData as(Name alias) {
        return new AppAttachmentData(alias, this);
    }

    @Override
    public AppAttachmentData as(Table<?> alias) {
        return new AppAttachmentData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAttachmentData rename(String name) {
        return new AppAttachmentData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAttachmentData rename(Name name) {
        return new AppAttachmentData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppAttachmentData rename(Table<?> name) {
        return new AppAttachmentData(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, byte[]> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super byte[], ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super byte[], ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
