/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.AppTranslationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTranslation extends TableImpl<AppTranslationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.app_translation</code>
     */
    public static final AppTranslation APP_TRANSLATION = new AppTranslation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppTranslationRecord> getRecordType() {
        return AppTranslationRecord.class;
    }

    /**
     * The column <code>public.app_translation.id</code>.
     */
    public final TableField<AppTranslationRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.locale</code>.
     */
    public final TableField<AppTranslationRecord, String> LOCALE = createField(DSL.name("locale"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.tag</code>.
     */
    public final TableField<AppTranslationRecord, String> TAG = createField(DSL.name("tag"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.process_name</code>.
     */
    public final TableField<AppTranslationRecord, String> PROCESS_NAME = createField(DSL.name("process_name"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.translation</code>.
     */
    public final TableField<AppTranslationRecord, String> TRANSLATION = createField(DSL.name("translation"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.app_translation.created</code>.
     */
    public final TableField<AppTranslationRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.app_translation.modified</code>.
     */
    public final TableField<AppTranslationRecord, Timestamp> MODIFIED = createField(DSL.name("modified"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    private AppTranslation(Name alias, Table<AppTranslationRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppTranslation(Name alias, Table<AppTranslationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.app_translation</code> table reference
     */
    public AppTranslation(String alias) {
        this(DSL.name(alias), APP_TRANSLATION);
    }

    /**
     * Create an aliased <code>public.app_translation</code> table reference
     */
    public AppTranslation(Name alias) {
        this(alias, APP_TRANSLATION);
    }

    /**
     * Create a <code>public.app_translation</code> table reference
     */
    public AppTranslation() {
        this(DSL.name("app_translation"), null);
    }

    public <O extends Record> AppTranslation(Table<O> child, ForeignKey<O, AppTranslationRecord> key) {
        super(child, key, APP_TRANSLATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AppTranslationRecord> getPrimaryKey() {
        return Keys.PK_APP_TRANSLATION;
    }

    @Override
    public List<UniqueKey<AppTranslationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_APP_TRANSLATION);
    }

    @Override
    public AppTranslation as(String alias) {
        return new AppTranslation(DSL.name(alias), this);
    }

    @Override
    public AppTranslation as(Name alias) {
        return new AppTranslation(alias, this);
    }

    @Override
    public AppTranslation as(Table<?> alias) {
        return new AppTranslation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppTranslation rename(String name) {
        return new AppTranslation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppTranslation rename(Name name) {
        return new AppTranslation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppTranslation rename(Table<?> name) {
        return new AppTranslation(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super String, ? super String, ? super String, ? super String, ? super String, ? super Timestamp, ? super Timestamp, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super String, ? super String, ? super String, ? super String, ? super String, ? super Timestamp, ? super Timestamp, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
