/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.CorgeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Corge extends TableImpl<CorgeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.corge</code>
     */
    public static final Corge CORGE = new Corge();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorgeRecord> getRecordType() {
        return CorgeRecord.class;
    }

    /**
     * The column <code>public.corge.id</code>.
     */
    public final TableField<CorgeRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge.version</code>.
     */
    public final TableField<CorgeRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge.name</code>.
     */
    public final TableField<CorgeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.corge.num</code>.
     */
    public final TableField<CorgeRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.corge.num2</code>.
     */
    public final TableField<CorgeRecord, Integer> NUM2 = createField(DSL.name("num2"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.corge.type_id</code>.
     */
    public final TableField<CorgeRecord, String> TYPE_ID = createField(DSL.name("type_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge.created</code>.
     */
    public final TableField<CorgeRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.corge.description</code>.
     */
    public final TableField<CorgeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.corge.owner_id</code>.
     */
    public final TableField<CorgeRecord, String> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge.flag</code>.
     */
    public final TableField<CorgeRecord, Boolean> FLAG = createField(DSL.name("flag"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.corge.type2</code>.
     */
    public final TableField<CorgeRecord, String> TYPE2 = createField(DSL.name("type2"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge.modified</code>.
     */
    public final TableField<CorgeRecord, Timestamp> MODIFIED = createField(DSL.name("modified"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    private Corge(Name alias, Table<CorgeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Corge(Name alias, Table<CorgeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.corge</code> table reference
     */
    public Corge(String alias) {
        this(DSL.name(alias), CORGE);
    }

    /**
     * Create an aliased <code>public.corge</code> table reference
     */
    public Corge(Name alias) {
        this(alias, CORGE);
    }

    /**
     * Create a <code>public.corge</code> table reference
     */
    public Corge() {
        this(DSL.name("corge"), null);
    }

    public <O extends Record> Corge(Table<O> child, ForeignKey<O, CorgeRecord> key) {
        super(child, key, CORGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CorgeRecord> getPrimaryKey() {
        return Keys.PK_CORGE;
    }

    @Override
    public List<ForeignKey<CorgeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CORGE__FK_CORGE_TYPE_ID, Keys.CORGE__FK_CORGE_OWNER_ID, Keys.CORGE__FK_CORGE_TYPE2);
    }

    private transient CorgeType _fkCorgeTypeId;
    private transient AppUser _appUser;
    private transient CorgeType _fkCorgeType2;

    /**
     * Get the implicit join path to the <code>public.corge_type</code> table,
     * via the <code>fk_corge_type_id</code> key.
     */
    public CorgeType fkCorgeTypeId() {
        if (_fkCorgeTypeId == null)
            _fkCorgeTypeId = new CorgeType(this, Keys.CORGE__FK_CORGE_TYPE_ID);

        return _fkCorgeTypeId;
    }

    /**
     * Get the implicit join path to the <code>public.app_user</code> table.
     */
    public AppUser appUser() {
        if (_appUser == null)
            _appUser = new AppUser(this, Keys.CORGE__FK_CORGE_OWNER_ID);

        return _appUser;
    }

    /**
     * Get the implicit join path to the <code>public.corge_type</code> table,
     * via the <code>fk_corge_type2</code> key.
     */
    public CorgeType fkCorgeType2() {
        if (_fkCorgeType2 == null)
            _fkCorgeType2 = new CorgeType(this, Keys.CORGE__FK_CORGE_TYPE2);

        return _fkCorgeType2;
    }

    @Override
    public Corge as(String alias) {
        return new Corge(DSL.name(alias), this);
    }

    @Override
    public Corge as(Name alias) {
        return new Corge(alias, this);
    }

    @Override
    public Corge as(Table<?> alias) {
        return new Corge(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Corge rename(String name) {
        return new Corge(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Corge rename(Name name) {
        return new Corge(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Corge rename(Table<?> name) {
        return new Corge(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<String, String, String, Integer, Integer, String, Timestamp, String, String, Boolean, String, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super String, ? super Timestamp, ? super String, ? super String, ? super Boolean, ? super String, ? super Timestamp, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super String, ? super String, ? super String, ? super Integer, ? super Integer, ? super String, ? super Timestamp, ? super String, ? super String, ? super Boolean, ? super String, ? super Timestamp, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
