/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Indexes;
import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.CorgeAssocRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorgeAssoc extends TableImpl<CorgeAssocRecord> {

    private static final long serialVersionUID = -1539759519;

    /**
     * The reference instance of <code>public.corge_assoc</code>
     */
    public static final CorgeAssoc CORGE_ASSOC = new CorgeAssoc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorgeAssocRecord> getRecordType() {
        return CorgeAssocRecord.class;
    }

    /**
     * The column <code>public.corge_assoc.id</code>.
     */
    public final TableField<CorgeAssocRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.version</code>.
     */
    public final TableField<CorgeAssocRecord, String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.name</code>.
     */
    public final TableField<CorgeAssocRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.num</code>.
     */
    public final TableField<CorgeAssocRecord, Integer> NUM = createField("num", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.description</code>.
     */
    public final TableField<CorgeAssocRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc() {
        this(DSL.name("corge_assoc"), null);
    }

    /**
     * Create an aliased <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc(String alias) {
        this(DSL.name(alias), CORGE_ASSOC);
    }

    /**
     * Create an aliased <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc(Name alias) {
        this(alias, CORGE_ASSOC);
    }

    private CorgeAssoc(Name alias, Table<CorgeAssocRecord> aliased) {
        this(alias, aliased, null);
    }

    private CorgeAssoc(Name alias, Table<CorgeAssocRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_CORGE_ASSOC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CorgeAssocRecord> getPrimaryKey() {
        return Keys.PK_CORGE_ASSOC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CorgeAssocRecord>> getKeys() {
        return Arrays.<UniqueKey<CorgeAssocRecord>>asList(Keys.PK_CORGE_ASSOC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorgeAssoc as(String alias) {
        return new CorgeAssoc(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorgeAssoc as(Name alias) {
        return new CorgeAssoc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CorgeAssoc rename(String name) {
        return new CorgeAssoc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorgeAssoc rename(Name name) {
        return new CorgeAssoc(name, null);
    }
}
