/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.CorgeAssocRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorgeAssoc extends TableImpl<CorgeAssocRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.corge_assoc</code>
     */
    public static final CorgeAssoc CORGE_ASSOC = new CorgeAssoc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorgeAssocRecord> getRecordType() {
        return CorgeAssocRecord.class;
    }

    /**
     * The column <code>public.corge_assoc.id</code>.
     */
    public final TableField<CorgeAssocRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.version</code>.
     */
    public final TableField<CorgeAssocRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.name</code>.
     */
    public final TableField<CorgeAssocRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.num</code>.
     */
    public final TableField<CorgeAssocRecord, Integer> NUM = createField(DSL.name("num"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.corge_assoc.description</code>.
     */
    public final TableField<CorgeAssocRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private CorgeAssoc(Name alias, Table<CorgeAssocRecord> aliased) {
        this(alias, aliased, null);
    }

    private CorgeAssoc(Name alias, Table<CorgeAssocRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc(String alias) {
        this(DSL.name(alias), CORGE_ASSOC);
    }

    /**
     * Create an aliased <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc(Name alias) {
        this(alias, CORGE_ASSOC);
    }

    /**
     * Create a <code>public.corge_assoc</code> table reference
     */
    public CorgeAssoc() {
        this(DSL.name("corge_assoc"), null);
    }

    public <O extends Record> CorgeAssoc(Table<O> child, ForeignKey<O, CorgeAssocRecord> key) {
        super(child, key, CORGE_ASSOC);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CorgeAssocRecord> getPrimaryKey() {
        return Keys.PK_CORGE_ASSOC;
    }

    @Override
    public CorgeAssoc as(String alias) {
        return new CorgeAssoc(DSL.name(alias), this);
    }

    @Override
    public CorgeAssoc as(Name alias) {
        return new CorgeAssoc(alias, this);
    }

    @Override
    public CorgeAssoc as(Table<?> alias) {
        return new CorgeAssoc(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CorgeAssoc rename(String name) {
        return new CorgeAssoc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorgeAssoc rename(Name name) {
        return new CorgeAssoc(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CorgeAssoc rename(Table<?> name) {
        return new CorgeAssoc(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super String, ? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
