/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.FooTypeRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FooType extends TableImpl<FooTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.foo_type</code>
     */
    public static final FooType FOO_TYPE = new FooType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FooTypeRecord> getRecordType() {
        return FooTypeRecord.class;
    }

    /**
     * The column <code>public.foo_type.ordinal</code>.
     */
    public final TableField<FooTypeRecord, Integer> ORDINAL = createField(DSL.name("ordinal"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.foo_type.name</code>.
     */
    public final TableField<FooTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private FooType(Name alias, Table<FooTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private FooType(Name alias, Table<FooTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(String alias) {
        this(DSL.name(alias), FOO_TYPE);
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(Name alias) {
        this(alias, FOO_TYPE);
    }

    /**
     * Create a <code>public.foo_type</code> table reference
     */
    public FooType() {
        this(DSL.name("foo_type"), null);
    }

    public <O extends Record> FooType(Table<O> child, ForeignKey<O, FooTypeRecord> key) {
        super(child, key, FOO_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FooTypeRecord> getPrimaryKey() {
        return Keys.PK_FOO_TYPE;
    }

    @Override
    public List<UniqueKey<FooTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FOO_TYPE_NAME_KEY);
    }

    @Override
    public FooType as(String alias) {
        return new FooType(DSL.name(alias), this);
    }

    @Override
    public FooType as(Name alias) {
        return new FooType(alias, this);
    }

    @Override
    public FooType as(Table<?> alias) {
        return new FooType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(String name) {
        return new FooType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(Name name) {
        return new FooType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(Table<?> name) {
        return new FooType(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
