/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.QuxBRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuxB extends TableImpl<QuxBRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.qux_b</code>
     */
    public static final QuxB QUX_B = new QuxB();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuxBRecord> getRecordType() {
        return QuxBRecord.class;
    }

    /**
     * The column <code>public.qux_b.id</code>.
     */
    public final TableField<QuxBRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.qux_b.name</code>.
     */
    public final TableField<QuxBRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.qux_b.value</code>.
     */
    public final TableField<QuxBRecord, Integer> VALUE = createField(DSL.name("value"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.qux_b.description</code>.
     */
    public final TableField<QuxBRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private QuxB(Name alias, Table<QuxBRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuxB(Name alias, Table<QuxBRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.qux_b</code> table reference
     */
    public QuxB(String alias) {
        this(DSL.name(alias), QUX_B);
    }

    /**
     * Create an aliased <code>public.qux_b</code> table reference
     */
    public QuxB(Name alias) {
        this(alias, QUX_B);
    }

    /**
     * Create a <code>public.qux_b</code> table reference
     */
    public QuxB() {
        this(DSL.name("qux_b"), null);
    }

    public <O extends Record> QuxB(Table<O> child, ForeignKey<O, QuxBRecord> key) {
        super(child, key, QUX_B);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuxBRecord> getPrimaryKey() {
        return Keys.PK_QUX_B;
    }

    @Override
    public List<UniqueKey<QuxBRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.QUX_B_NAME_KEY);
    }

    @Override
    public QuxB as(String alias) {
        return new QuxB(DSL.name(alias), this);
    }

    @Override
    public QuxB as(Name alias) {
        return new QuxB(alias, this);
    }

    @Override
    public QuxB as(Table<?> alias) {
        return new QuxB(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxB rename(String name) {
        return new QuxB(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxB rename(Name name) {
        return new QuxB(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxB rename(Table<?> name) {
        return new QuxB(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
