/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.QuxDRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuxD extends TableImpl<QuxDRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.qux_d</code>
     */
    public static final QuxD QUX_D = new QuxD();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuxDRecord> getRecordType() {
        return QuxDRecord.class;
    }

    /**
     * The column <code>public.qux_d.id</code>.
     */
    public final TableField<QuxDRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.qux_d.name</code>.
     */
    public final TableField<QuxDRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.qux_d.value</code>.
     */
    public final TableField<QuxDRecord, Integer> VALUE = createField(DSL.name("value"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.qux_d.description</code>.
     */
    public final TableField<QuxDRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private QuxD(Name alias, Table<QuxDRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuxD(Name alias, Table<QuxDRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.qux_d</code> table reference
     */
    public QuxD(String alias) {
        this(DSL.name(alias), QUX_D);
    }

    /**
     * Create an aliased <code>public.qux_d</code> table reference
     */
    public QuxD(Name alias) {
        this(alias, QUX_D);
    }

    /**
     * Create a <code>public.qux_d</code> table reference
     */
    public QuxD() {
        this(DSL.name("qux_d"), null);
    }

    public <O extends Record> QuxD(Table<O> child, ForeignKey<O, QuxDRecord> key) {
        super(child, key, QUX_D);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<QuxDRecord> getPrimaryKey() {
        return Keys.PK_QUX_D;
    }

    @Override
    public List<UniqueKey<QuxDRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.QUX_D_NAME_KEY);
    }

    @Override
    public QuxD as(String alias) {
        return new QuxD(DSL.name(alias), this);
    }

    @Override
    public QuxD as(Name alias) {
        return new QuxD(alias, this);
    }

    @Override
    public QuxD as(Table<?> alias) {
        return new QuxD(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxD rename(String name) {
        return new QuxD(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxD rename(Name name) {
        return new QuxD(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxD rename(Table<?> name) {
        return new QuxD(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
