/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Indexes;
import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.QuxDRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuxD extends TableImpl<QuxDRecord> {

    private static final long serialVersionUID = -1473495765;

    /**
     * The reference instance of <code>public.qux_d</code>
     */
    public static final QuxD QUX_D = new QuxD();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuxDRecord> getRecordType() {
        return QuxDRecord.class;
    }

    /**
     * The column <code>public.qux_d.id</code>.
     */
    public final TableField<QuxDRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.qux_d.name</code>.
     */
    public final TableField<QuxDRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.qux_d.value</code>.
     */
    public final TableField<QuxDRecord, Integer> VALUE = createField("value", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.qux_d.description</code>.
     */
    public final TableField<QuxDRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.qux_d</code> table reference
     */
    public QuxD() {
        this(DSL.name("qux_d"), null);
    }

    /**
     * Create an aliased <code>public.qux_d</code> table reference
     */
    public QuxD(String alias) {
        this(DSL.name(alias), QUX_D);
    }

    /**
     * Create an aliased <code>public.qux_d</code> table reference
     */
    public QuxD(Name alias) {
        this(alias, QUX_D);
    }

    private QuxD(Name alias, Table<QuxDRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuxD(Name alias, Table<QuxDRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_QUX_D, Indexes.QUX_D_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QuxDRecord> getPrimaryKey() {
        return Keys.PK_QUX_D;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QuxDRecord>> getKeys() {
        return Arrays.<UniqueKey<QuxDRecord>>asList(Keys.PK_QUX_D, Keys.QUX_D_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuxD as(String alias) {
        return new QuxD(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuxD as(Name alias) {
        return new QuxD(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxD rename(String name) {
        return new QuxD(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxD rename(Name name) {
        return new QuxD(name, null);
    }
}
