/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Indexes;
import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.QuxTopRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuxTop extends TableImpl<QuxTopRecord> {

    private static final long serialVersionUID = -1448726372;

    /**
     * The reference instance of <code>public.qux_top</code>
     */
    public static final QuxTop QUX_TOP = new QuxTop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuxTopRecord> getRecordType() {
        return QuxTopRecord.class;
    }

    /**
     * The column <code>public.qux_top.id</code>.
     */
    public final TableField<QuxTopRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.qux_top.name</code>.
     */
    public final TableField<QuxTopRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.qux_top.qux_mid_id</code>.
     */
    public final TableField<QuxTopRecord, String> QUX_MID_ID = createField("qux_mid_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.qux_top</code> table reference
     */
    public QuxTop() {
        this(DSL.name("qux_top"), null);
    }

    /**
     * Create an aliased <code>public.qux_top</code> table reference
     */
    public QuxTop(String alias) {
        this(DSL.name(alias), QUX_TOP);
    }

    /**
     * Create an aliased <code>public.qux_top</code> table reference
     */
    public QuxTop(Name alias) {
        this(alias, QUX_TOP);
    }

    private QuxTop(Name alias, Table<QuxTopRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuxTop(Name alias, Table<QuxTopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_QUX_TOP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QuxTopRecord> getPrimaryKey() {
        return Keys.PK_QUX_TOP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QuxTopRecord>> getKeys() {
        return Arrays.<UniqueKey<QuxTopRecord>>asList(Keys.PK_QUX_TOP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<QuxTopRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<QuxTopRecord, ?>>asList(Keys.QUX_TOP__FK_QUX_MID_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuxTop as(String alias) {
        return new QuxTop(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuxTop as(Name alias) {
        return new QuxTop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxTop rename(String name) {
        return new QuxTop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuxTop rename(Name name) {
        return new QuxTop(name, null);
    }
}
