/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.SumPerMonthRecord;

import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SumPerMonth extends TableImpl<SumPerMonthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sum_per_month</code>
     */
    public static final SumPerMonth SUM_PER_MONTH = new SumPerMonth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SumPerMonthRecord> getRecordType() {
        return SumPerMonthRecord.class;
    }

    /**
     * The column <code>public.sum_per_month.month</code>.
     */
    public final TableField<SumPerMonthRecord, Integer> MONTH = createField(DSL.name("month"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sum_per_month.year</code>.
     */
    public final TableField<SumPerMonthRecord, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sum_per_month.sum</code>.
     */
    public final TableField<SumPerMonthRecord, Long> SUM = createField(DSL.name("sum"), SQLDataType.BIGINT, this, "");

    private SumPerMonth(Name alias, Table<SumPerMonthRecord> aliased) {
        this(alias, aliased, null);
    }

    private SumPerMonth(Name alias, Table<SumPerMonthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("""
        create view "sum_per_month" as  SELECT (date_part('month'::text, bar.created))::integer AS month,
          (date_part('year'::text, bar.created))::integer AS year,
          sum((bar.numa + bar.numb)) AS sum
         FROM bar
        GROUP BY ((date_part('year'::text, bar.created))::integer), ((date_part('month'::text, bar.created))::integer);
        """));
    }

    /**
     * Create an aliased <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth(String alias) {
        this(DSL.name(alias), SUM_PER_MONTH);
    }

    /**
     * Create an aliased <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth(Name alias) {
        this(alias, SUM_PER_MONTH);
    }

    /**
     * Create a <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth() {
        this(DSL.name("sum_per_month"), null);
    }

    public <O extends Record> SumPerMonth(Table<O> child, ForeignKey<O, SumPerMonthRecord> key) {
        super(child, key, SUM_PER_MONTH);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public SumPerMonth as(String alias) {
        return new SumPerMonth(DSL.name(alias), this);
    }

    @Override
    public SumPerMonth as(Name alias) {
        return new SumPerMonth(alias, this);
    }

    @Override
    public SumPerMonth as(Table<?> alias) {
        return new SumPerMonth(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SumPerMonth rename(String name) {
        return new SumPerMonth(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SumPerMonth rename(Name name) {
        return new SumPerMonth(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SumPerMonth rename(Table<?> name) {
        return new SumPerMonth(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Integer, ? super Integer, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Integer, ? super Integer, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
