/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.SumPerMonthRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SumPerMonth extends TableImpl<SumPerMonthRecord> {

    private static final long serialVersionUID = -932852193;

    /**
     * The reference instance of <code>public.sum_per_month</code>
     */
    public static final SumPerMonth SUM_PER_MONTH = new SumPerMonth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SumPerMonthRecord> getRecordType() {
        return SumPerMonthRecord.class;
    }

    /**
     * The column <code>public.sum_per_month.month</code>.
     */
    public final TableField<SumPerMonthRecord, Integer> MONTH = createField("month", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sum_per_month.year</code>.
     */
    public final TableField<SumPerMonthRecord, Integer> YEAR = createField("year", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sum_per_month.sum</code>.
     */
    public final TableField<SumPerMonthRecord, Long> SUM = createField("sum", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth() {
        this(DSL.name("sum_per_month"), null);
    }

    /**
     * Create an aliased <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth(String alias) {
        this(DSL.name(alias), SUM_PER_MONTH);
    }

    /**
     * Create an aliased <code>public.sum_per_month</code> table reference
     */
    public SumPerMonth(Name alias) {
        this(alias, SUM_PER_MONTH);
    }

    private SumPerMonth(Name alias, Table<SumPerMonthRecord> aliased) {
        this(alias, aliased, null);
    }

    private SumPerMonth(Name alias, Table<SumPerMonthRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonth as(String alias) {
        return new SumPerMonth(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SumPerMonth as(Name alias) {
        return new SumPerMonth(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SumPerMonth rename(String name) {
        return new SumPerMonth(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SumPerMonth rename(Name name) {
        return new SumPerMonth(name, null);
    }
}
