/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables;


import de.quinscape.automatontest.domain.Keys;
import de.quinscape.automatontest.domain.Public;
import de.quinscape.automatontest.domain.tables.records.WaldoRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waldo extends TableImpl<WaldoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.waldo</code>
     */
    public static final Waldo WALDO = new Waldo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WaldoRecord> getRecordType() {
        return WaldoRecord.class;
    }

    /**
     * The column <code>public.waldo.id</code>.
     */
    public final TableField<WaldoRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.waldo.name</code>.
     */
    public final TableField<WaldoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.waldo.timestamp</code>.
     */
    public final TableField<WaldoRecord, Timestamp> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.TIMESTAMP(6).nullable(false), this, "");

    /**
     * The column <code>public.waldo.date</code>.
     */
    public final TableField<WaldoRecord, Date> DATE = createField(DSL.name("date"), SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.waldo.opt1</code>.
     */
    public final TableField<WaldoRecord, Timestamp> OPT1 = createField(DSL.name("opt1"), SQLDataType.TIMESTAMP(6), this, "");

    /**
     * The column <code>public.waldo.opt2</code>.
     */
    public final TableField<WaldoRecord, Date> OPT2 = createField(DSL.name("opt2"), SQLDataType.DATE, this, "");

    private Waldo(Name alias, Table<WaldoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Waldo(Name alias, Table<WaldoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.waldo</code> table reference
     */
    public Waldo(String alias) {
        this(DSL.name(alias), WALDO);
    }

    /**
     * Create an aliased <code>public.waldo</code> table reference
     */
    public Waldo(Name alias) {
        this(alias, WALDO);
    }

    /**
     * Create a <code>public.waldo</code> table reference
     */
    public Waldo() {
        this(DSL.name("waldo"), null);
    }

    public <O extends Record> Waldo(Table<O> child, ForeignKey<O, WaldoRecord> key) {
        super(child, key, WALDO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<WaldoRecord> getPrimaryKey() {
        return Keys.PK_WALDO;
    }

    @Override
    public Waldo as(String alias) {
        return new Waldo(DSL.name(alias), this);
    }

    @Override
    public Waldo as(Name alias) {
        return new Waldo(alias, this);
    }

    @Override
    public Waldo as(Table<?> alias) {
        return new Waldo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Waldo rename(String name) {
        return new Waldo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Waldo rename(Name name) {
        return new Waldo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Waldo rename(Table<?> name) {
        return new Waldo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, Timestamp, Date, Timestamp, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super String, ? super String, ? super Timestamp, ? super Date, ? super Timestamp, ? super Date, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super String, ? super String, ? super Timestamp, ? super Date, ? super Timestamp, ? super Date, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
