/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "customer", schema = "public", indexes = {
    @Index(name = "pk_customer", unique = true, columnList = "id ASC")
})
public class Customer extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -1170032765;

    private String id;
    private String salutation;
    private String number;
    private String name;
    private String billingAddressId;
    private String deliveryAddressId;

    public Customer() {}

    public Customer(Customer value) {
        this.id = value.id;
        this.salutation = value.salutation;
        this.number = value.number;
        this.name = value.name;
        this.billingAddressId = value.billingAddressId;
        this.deliveryAddressId = value.deliveryAddressId;
    }

    public Customer(
        String id,
        String salutation,
        String number,
        String name,
        String billingAddressId,
        String deliveryAddressId
    ) {
        this.id = id;
        this.salutation = salutation;
        this.number = number;
        this.name = name;
        this.billingAddressId = billingAddressId;
        this.deliveryAddressId = deliveryAddressId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "salutation", length = 50)
    @Size(max = 50)
    public String getSalutation() {
        return this.salutation;
    }

    public void setSalutation(String salutation) {
        this.salutation = salutation;
    }

    @Column(name = "number", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Column(name = "name", nullable = false, length = 120)
    @NotNull
    @Size(max = 120)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "billing_address_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getBillingAddressId() {
        return this.billingAddressId;
    }

    public void setBillingAddressId(String billingAddressId) {
        this.billingAddressId = billingAddressId;
    }

    @Column(name = "delivery_address_id", length = 36)
    @Size(max = 36)
    public String getDeliveryAddressId() {
        return this.deliveryAddressId;
    }

    public void setDeliveryAddressId(String deliveryAddressId) {
        this.deliveryAddressId = deliveryAddressId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customer (");

        sb.append(id);
        sb.append(", ").append(salutation);
        sb.append(", ").append(number);
        sb.append(", ").append(name);
        sb.append(", ").append(billingAddressId);
        sb.append(", ").append(deliveryAddressId);

        sb.append(")");
        return sb.toString();
    }
}
