/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "foo_type",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "foo_type_name_key", columnNames = { "name" })
    }
)
public class FooType extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer ordinal;
    private String name;

    public FooType() {}

    public FooType(FooType value) {
        this.ordinal = value.ordinal;
        this.name = value.name;
    }

    public FooType(
        Integer ordinal,
        String name
    ) {
        this.ordinal = ordinal;
        this.name = name;
    }

    /**
     * Getter for <code>public.foo_type.ordinal</code>.
     */
    @Id
    @Column(name = "ordinal", nullable = false)
    @NotNull
    public Integer getOrdinal() {
        return this.ordinal;
    }

    /**
     * Setter for <code>public.foo_type.ordinal</code>.
     */
    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    /**
     * Getter for <code>public.foo_type.name</code>.
     */
    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.foo_type.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FooType other = (FooType) obj;
        if (this.ordinal == null) {
            if (other.ordinal != null)
                return false;
        }
        else if (!this.ordinal.equals(other.ordinal))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.ordinal == null) ? 0 : this.ordinal.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FooType (");

        sb.append(ordinal);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
