/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;
import de.quinscape.domainql.jsonb.JSONB;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "grid_columns", schema = "public", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"type_name", "owner_id"})
}, indexes = {
    @Index(name = "grid_columns_type_name_owner_id_key", unique = true, columnList = "type_name ASC, owner_id ASC"),
    @Index(name = "pk_grid_columns", unique = true, columnList = "id ASC")
})
public class GridColumns extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -412792571;

    private String id;
    private String typeName;
    private JSONB  columns;
    private String ownerId;

    public GridColumns() {}

    public GridColumns(GridColumns value) {
        this.id = value.id;
        this.typeName = value.typeName;
        this.columns = value.columns;
        this.ownerId = value.ownerId;
    }

    public GridColumns(
        String id,
        String typeName,
        JSONB  columns,
        String ownerId
    ) {
        this.id = id;
        this.typeName = typeName;
        this.columns = columns;
        this.ownerId = ownerId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "type_name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Column(name = "columns")
    public JSONB getColumns() {
        return this.columns;
    }

    public void setColumns(JSONB columns) {
        this.columns = columns;
    }

    @Column(name = "owner_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GridColumns (");

        sb.append(id);
        sb.append(", ").append(typeName);
        sb.append(", ").append(columns);
        sb.append(", ").append(ownerId);

        sb.append(")");
        return sb.toString();
    }
}
