/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "meta_config", schema = "public", indexes = {
    @Index(name = "pk_meta_config", unique = true, columnList = "id ASC")
})
public class MetaConfig extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -861078647;

    private String     id;
    private String     name;
    private String     text;
    private Integer    num;
    private BigDecimal bigNum;
    private Boolean    flag;
    private Timestamp  timestamp;
    private Date       date;
    private String     type;
    private String     url;
    private String     attachmentId;
    private String     corgeTypeId;

    public MetaConfig() {}

    public MetaConfig(MetaConfig value) {
        this.id = value.id;
        this.name = value.name;
        this.text = value.text;
        this.num = value.num;
        this.bigNum = value.bigNum;
        this.flag = value.flag;
        this.timestamp = value.timestamp;
        this.date = value.date;
        this.type = value.type;
        this.url = value.url;
        this.attachmentId = value.attachmentId;
        this.corgeTypeId = value.corgeTypeId;
    }

    public MetaConfig(
        String     id,
        String     name,
        String     text,
        Integer    num,
        BigDecimal bigNum,
        Boolean    flag,
        Timestamp  timestamp,
        Date       date,
        String     type,
        String     url,
        String     attachmentId,
        String     corgeTypeId
    ) {
        this.id = id;
        this.name = name;
        this.text = text;
        this.num = num;
        this.bigNum = bigNum;
        this.flag = flag;
        this.timestamp = timestamp;
        this.date = date;
        this.type = type;
        this.url = url;
        this.attachmentId = attachmentId;
        this.corgeTypeId = corgeTypeId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "text")
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    @Column(name = "num", precision = 32)
    public Integer getNum() {
        return this.num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    @Column(name = "big_num", precision = 13, scale = 10)
    public BigDecimal getBigNum() {
        return this.bigNum;
    }

    public void setBigNum(BigDecimal bigNum) {
        this.bigNum = bigNum;
    }

    @Column(name = "flag")
    public Boolean getFlag() {
        return this.flag;
    }

    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    @Column(name = "timestamp")
    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name = "date")
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "type", length = 100)
    @Size(max = 100)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "url")
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "attachment_id", length = 36)
    @Size(max = 36)
    public String getAttachmentId() {
        return this.attachmentId;
    }

    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId;
    }

    @Column(name = "corge_type_id", length = 36)
    @Size(max = 36)
    public String getCorgeTypeId() {
        return this.corgeTypeId;
    }

    public void setCorgeTypeId(String corgeTypeId) {
        this.corgeTypeId = corgeTypeId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaConfig (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(text);
        sb.append(", ").append(num);
        sb.append(", ").append(bigNum);
        sb.append(", ").append(flag);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(date);
        sb.append(", ").append(type);
        sb.append(", ").append(url);
        sb.append(", ").append(attachmentId);
        sb.append(", ").append(corgeTypeId);

        sb.append(")");
        return sb.toString();
    }
}
