/*
 * This file is generated by jOOQ.
 */
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "node",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "uc_node_name", columnNames = { "name" })
    }
)
public class Node extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String name;
    private String parentId;
    private Integer type;

    public Node() {}

    public Node(Node value) {
        this.id = value.id;
        this.name = value.name;
        this.parentId = value.parentId;
        this.type = value.type;
    }

    public Node(
        String id,
        String name,
        String parentId,
        Integer type
    ) {
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.type = type;
    }

    /**
     * Getter for <code>public.node.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.node.id</code>.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.node.name</code>.
     */
    @Column(name = "name", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.node.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.node.parent_id</code>.
     */
    @Column(name = "parent_id", length = 36)
    @Size(max = 36)
    public String getParentId() {
        return this.parentId;
    }

    /**
     * Setter for <code>public.node.parent_id</code>.
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * Getter for <code>public.node.type</code>.
     */
    @Column(name = "type", nullable = false)
    @NotNull
    public Integer getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.node.type</code>.
     */
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Node other = (Node) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.parentId == null) {
            if (other.parentId != null)
                return false;
        }
        else if (!this.parentId.equals(other.parentId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.parentId == null) ? 0 : this.parentId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Node (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(parentId);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
