/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.generic.DomainObject;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "order", schema = "public", indexes = {
    @Index(name = "fki_order_order_shipping_type", columnList = "shipping_type ASC"),
    @Index(name = "fki_order_order_status", columnList = "status ASC"),
    @Index(name = "pk_order", unique = true, columnList = "id ASC")
})
public class Order implements DomainObject, Serializable {

    private static final long serialVersionUID = 1650316248;

    private String    id;
    private Long      sum;
    private String    trackingNumber;
    private Integer   shippingType;
    private String    status;
    private String    customerId;
    private String    number;
    private Timestamp accepted;

    public Order() {}

    public Order(Order value) {
        this.id = value.id;
        this.sum = value.sum;
        this.trackingNumber = value.trackingNumber;
        this.shippingType = value.shippingType;
        this.status = value.status;
        this.customerId = value.customerId;
        this.number = value.number;
        this.accepted = value.accepted;
    }

    public Order(
        String    id,
        Long      sum,
        String    trackingNumber,
        Integer   shippingType,
        String    status,
        String    customerId,
        String    number,
        Timestamp accepted
    ) {
        this.id = id;
        this.sum = sum;
        this.trackingNumber = trackingNumber;
        this.shippingType = shippingType;
        this.status = status;
        this.customerId = customerId;
        this.number = number;
        this.accepted = accepted;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "sum", nullable = false, precision = 64)
    @NotNull
    public Long getSum() {
        return this.sum;
    }

    public void setSum(Long sum) {
        this.sum = sum;
    }

    @Column(name = "tracking_number", length = 255)
    @Size(max = 255)
    public String getTrackingNumber() {
        return this.trackingNumber;
    }

    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    @Column(name = "shipping_type", nullable = false, precision = 32)
    @NotNull
    public Integer getShippingType() {
        return this.shippingType;
    }

    public void setShippingType(Integer shippingType) {
        this.shippingType = shippingType;
    }

    @Column(name = "status", nullable = false, length = 16)
    @NotNull
    @Size(max = 16)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "customer_id", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    @Column(name = "number", nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Column(name = "accepted")
    public Timestamp getAccepted() {
        return this.accepted;
    }

    public void setAccepted(Timestamp accepted) {
        this.accepted = accepted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Order (");

        sb.append(id);
        sb.append(", ").append(sum);
        sb.append(", ").append(trackingNumber);
        sb.append(", ").append(shippingType);
        sb.append(", ").append(status);
        sb.append(", ").append(customerId);
        sb.append(", ").append(number);
        sb.append(", ").append(accepted);

        sb.append(")");
        return sb.toString();
    }
}
