/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automatontest.domain.tables.pojos;


import de.quinscape.domainql.jooq.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "qux_mid", schema = "public", indexes = {
    @Index(name = "pk_qux_mid", unique = true, columnList = "id ASC"),
    @Index(name = "qux_mid_name_key", unique = true, columnList = "name ASC")
})
public class QuxMid extends GeneratedDomainObject implements Serializable {

    private static final long serialVersionUID = -986959272;

    private String id;
    private String name;
    private String description;
    private String quxEId;

    public QuxMid() {}

    public QuxMid(QuxMid value) {
        this.id = value.id;
        this.name = value.name;
        this.description = value.description;
        this.quxEId = value.quxEId;
    }

    public QuxMid(
        String id,
        String name,
        String description,
        String quxEId
    ) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.quxEId = quxEId;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "qux_e_id", length = 36)
    @Size(max = 36)
    public String getQuxEId() {
        return this.quxEId;
    }

    public void setQuxEId(String quxEId) {
        this.quxEId = quxEId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuxMid (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(quxEId);

        sb.append(")");
        return sb.toString();
    }
}
